CREATE TABLE EP_ESTADOS
(
  COD_EST  VARCHAR2(2 BYTE),
  NOM_EST  VARCHAR2(20 BYTE)
);

COMMENT ON TABLE EP_ESTADOS IS 'ESTADOS DE LOS ESTUDIOS PREVIOS';

COMMENT ON COLUMN EP_ESTADOS.COD_EST IS 'CODIGO';

COMMENT ON COLUMN EP_ESTADOS.NOM_EST IS 'NOMBRE';


CREATE UNIQUE INDEX EP_ESTADOS_PK ON EP_ESTADOS (COD_EST);


ALTER TABLE EP_ESTADOS ADD (
  CONSTRAINT EP_ESTADOS_PK
 PRIMARY KEY (COD_EST));
