ALTER TABLE PACTIVIDADES
 ADD (TIP_PLA  VARCHAR2(2 BYTE));
 
 ALTER TABLE PCRONOGRAMAS
 ADD (TIP_PLA  VARCHAR2(2 BYTE));


ALTER TABLE PACTIVIDADES
 ADD CONSTRAINT FK_PACTI_TIP_PLA
 FOREIGN KEY (TIP_PLA) 
 REFERENCES PL_TIPOS_PLANTILLA (COD_TIP);

 ALTER TABLE PCRONOGRAMAS
 ADD CONSTRAINT FK_PCRONO_TIP_PLA
 FOREIGN KEY (TIP_PLA) 
 REFERENCES PL_TIPOS_PLANTILLA (COD_TIP);

 ALTER TABLE DOC_PLANTILLA
MODIFY(TITULO VARCHAR2(200 BYTE));