UPDATE PACTIVIDADES SET TIP_PLA = '1' WHERE COD_TPRO = 'TP01' AND COD_ACT = '1';
UPDATE PCRONOGRAMAS SET TIP_PLA = '2' WHERE COD_TPRO = 'TP01' AND COD_ACT = '18';

UPDATE PCRONOGRAMAS SET TIP_PLA = '1' WHERE COD_TPRO = 'TP01' AND COD_ACT = '1';
UPDATE PACTIVIDADES SET TIP_PLA = '2' WHERE COD_TPRO = 'TP01' AND COD_ACT = '18';
COMMIT;