INSERT INTO PL_PLANTILLA (ID, COD_TIP, TITULO, FEC_REV, NRO_REV, EST_PLA, DOC_MAX) SELECT ID, COD_TIP, TITULO, FEC_REV, NRO_REV, EST_PLA, DOC_MAX FROM SIRCC_MIG.PL_PLANTILLA;

INSERT INTO PL_SECCIONES (ID, ID_PLA, HTML) SELECT ID, ID_PLA, HTML FROM SIRCC_MIG.PL_SECCIONES;

COMMIT;



