CREATE TABLE EP_CLAUSULAS
(
  ID              NUMBER,
  ID_PLA          NUMBER,
  TIP_PLA         VARCHAR2(4 BYTE),
  CLA_TIT         VARCHAR2(200 BYTE),
  CLA_NUM         NUMBER,
  CLA_CAM         VARCHAR2(200 BYTE),
  CLA_PAR         VARCHAR2(200 BYTE),
  IDE_PMIN        NUMBER,
  TIP_PAR         VARCHAR2(2 BYTE),
  IS_ENTER_FINAL  VARCHAR2(1 BYTE),
  ORDEN           NUMBER(2),
  ID_EP           NUMBER,
  CLA_TEXTO       CLOB,
  CLA_CRUZADA     CLOB
);

COMMENT ON TABLE EP_CLAUSULAS IS 'COFIGURACION CLAUSULAS/PARRAFOS ESTUDIOS PREVIOS';

COMMENT ON COLUMN EP_CLAUSULAS.ID IS 'ID UNICO';

COMMENT ON COLUMN EP_CLAUSULAS.ID_PLA IS 'ID A PLANTILLA A LA QUE PERTENECE';

COMMENT ON COLUMN EP_CLAUSULAS.TIP_PLA IS 'TIPO DE PLANTILLA';

COMMENT ON COLUMN EP_CLAUSULAS.CLA_TIT IS 'TITULO DE LA CLAUSULA';

COMMENT ON COLUMN EP_CLAUSULAS.CLA_NUM IS 'NÚMERO DE LA CLAUSULA';

COMMENT ON COLUMN EP_CLAUSULAS.CLA_CAM IS 'CAMPOS RELACIONADOS';

COMMENT ON COLUMN EP_CLAUSULAS.CLA_PAR IS 'PARRAGRAFOS ASOCIADOS';

COMMENT ON COLUMN EP_CLAUSULAS.TIP_PAR IS 'TIPO DE PARRAFO';

COMMENT ON COLUMN EP_CLAUSULAS.ORDEN IS 'ORDEN DE IMPRESION';

COMMENT ON COLUMN EP_CLAUSULAS.ID_EP IS 'ID ESTUDIO PREVIO';


CREATE UNIQUE INDEX EP_CLAUSULAS_PK ON EP_CLAUSULAS
(ID);


ALTER TABLE EP_CLAUSULAS ADD (
  CONSTRAINT EP_CLAUSULAS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_CLAUSULAS ADD (
  CONSTRAINT EP_CLAUSULAS_EP 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));