CREATE TABLE EP_CONMUN
(
  ID       NUMBER,
  ID_EP    NUMBER,
  COD_MUN  VARCHAR2(5 BYTE)                     NOT NULL
);

COMMENT ON COLUMN EP_CONMUN.ID IS 'ID UNICO';

COMMENT ON COLUMN EP_CONMUN.ID_EP IS 'NUM ESTUDIO PREVIO';

COMMENT ON COLUMN EP_CONMUN.COD_MUN IS 'CODIGO DEL MUNICIPIO';


CREATE UNIQUE INDEX EP_CONMUN_PK ON EP_CONMUN
(ID);


ALTER TABLE EP_CONMUN ADD (
  CONSTRAINT EP_CONMUN_PK
 PRIMARY KEY
 (ID),
  UNIQUE (ID_EP, COD_MUN));

ALTER TABLE EP_CONMUN ADD (
  CONSTRAINT EP_CONMUN_MUNFK 
 FOREIGN KEY (COD_MUN) 
 REFERENCES MUNICIPIOS (COD_MUN),
  CONSTRAINT EP_CONMUN_EP 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));