CREATE TABLE EP_DT_UNIDADES
(
  COD_UNI  VARCHAR2(2 BYTE),
  NOM_UNI  VARCHAR2(200 BYTE)
);

COMMENT ON TABLE EP_DT_UNIDADES IS 'ep dt unidades';

COMMENT ON COLUMN EP_DT_UNIDADES.COD_UNI IS 'codigo';

COMMENT ON COLUMN EP_DT_UNIDADES.NOM_UNI IS 'nombre';


CREATE UNIQUE INDEX EP_DT_UNIDADES_PK ON EP_DT_UNIDADES
(COD_UNI);


ALTER TABLE EP_DT_UNIDADES ADD (
  CONSTRAINT EP_DT_UNIDADES_PK
 PRIMARY KEY
 (COD_UNI));
