CREATE TABLE EP_ESPTEC
(
  DESC_ITEM     VARCHAR2(300 BYTE),
  CANT_ITEM     INTEGER,
  UNI_ITEM      VARCHAR2(2 BYTE),
  VAL_UNI_ITEM  NUMBER(17,2),
  PORC_IVA      NUMBER(5,3),
  ID            NUMBER,
  USAP_REG      VARCHAR2(12 BYTE),
  FEC_REG       DATE,
  USAP_MOD      VARCHAR2(12 BYTE),
  FEC_MOD       DATE,
  ID_EP         NUMBER,
  GRUPO         NUMBER(2)
);

COMMENT ON TABLE EP_ESPTEC IS 'CARACTERISTICAS TECNICAS O ESPECIFICACIONES TECNICAS';

COMMENT ON COLUMN EP_ESPTEC.DESC_ITEM IS 'Descripción del Item';

COMMENT ON COLUMN EP_ESPTEC.CANT_ITEM IS 'Cantidad de Elementos';

COMMENT ON COLUMN EP_ESPTEC.UNI_ITEM IS 'Unidad ';

COMMENT ON COLUMN EP_ESPTEC.VAL_UNI_ITEM IS 'Valor Unitario';

COMMENT ON COLUMN EP_ESPTEC.PORC_IVA IS 'Porcentaje del IVA';

COMMENT ON COLUMN EP_ESPTEC.ID IS 'Id consecutvio';

COMMENT ON COLUMN EP_ESPTEC.USAP_REG IS 'usuario quien registra';

COMMENT ON COLUMN EP_ESPTEC.FEC_REG IS 'fecha de registro';

COMMENT ON COLUMN EP_ESPTEC.USAP_MOD IS 'usuario quien modifica por ultima vez';

COMMENT ON COLUMN EP_ESPTEC.FEC_MOD IS 'fecha de modificaicon';

COMMENT ON COLUMN EP_ESPTEC.ID_EP IS 'Id del Estudio Previo relacionado';

COMMENT ON COLUMN EP_ESPTEC.GRUPO IS 'Numero de Grupo';


CREATE UNIQUE INDEX EP_ESPTEC_PK ON EP_ESPTEC
(ID);


ALTER TABLE EP_ESPTEC ADD (
  CONSTRAINT EP_ESPTEC_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_ESPTEC ADD (
  CONSTRAINT EP_FK_UNIDADES 
 FOREIGN KEY (UNI_ITEM) 
 REFERENCES EP_DT_UNIDADES (COD_UNI),
  CONSTRAINT EP_ESPTEC_ID 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));