CREATE TABLE EP_FORMA_PAGO
(
  ID         NUMBER,
  ID_EP      NUMBER,
  ORD_FPAG   NUMBER,
  TIP_FPAG   VARCHAR2(2 BYTE),
  VAL_FPAG   NUMBER(17,4),
  POR_FPAG   NUMBER(17,4),
  CON_FPAG   VARCHAR2(2000 BYTE),
  PGEN_FPAG  CHAR(1 BYTE),
  FEC_REG    DATE,
  USAP_REG   VARCHAR2(12 BYTE),
  FEC_MOD    DATE,
  USAP_MOD   VARCHAR2(12 BYTE),
  CAN_PAG    NUMBER
);

COMMENT ON TABLE EP_FORMA_PAGO IS 'FORMA DE PAGO DEL ESTUDIO PREVIO PARA EL CONTRATO';

COMMENT ON COLUMN EP_FORMA_PAGO.ID IS 'ID UNICO';

COMMENT ON COLUMN EP_FORMA_PAGO.ID_EP IS 'ID DEL ESTUDIO PREVIO CORRESPONIENTE';

COMMENT ON COLUMN EP_FORMA_PAGO.ORD_FPAG IS 'ORDEN DEL PAGO PARA MOSTRAR';

COMMENT ON COLUMN EP_FORMA_PAGO.TIP_FPAG IS 'TIPO DE PAGO';

COMMENT ON COLUMN EP_FORMA_PAGO.VAL_FPAG IS 'VALOR A PAGAR';

COMMENT ON COLUMN EP_FORMA_PAGO.POR_FPAG IS 'PORCENTAJE DEL VALOR TOTAL';

COMMENT ON COLUMN EP_FORMA_PAGO.CON_FPAG IS 'CONDICIÓN DE LA FORMA DE PAGO';

COMMENT ON COLUMN EP_FORMA_PAGO.PGEN_FPAG IS 'PAGADO POR AL ENTIDAD? (S/N)';

COMMENT ON COLUMN EP_FORMA_PAGO.FEC_REG IS 'FEC DE REGISTRO';

COMMENT ON COLUMN EP_FORMA_PAGO.USAP_REG IS 'USUARIO QUIEN REGISTRO';

COMMENT ON COLUMN EP_FORMA_PAGO.FEC_MOD IS 'FECHA DE MODIFICACIÓN';

COMMENT ON COLUMN EP_FORMA_PAGO.USAP_MOD IS 'USUARIO QUIEN MODIFICO';

COMMENT ON COLUMN EP_FORMA_PAGO.CAN_PAG IS 'CANTIDAD DE PAGOS';


CREATE UNIQUE INDEX EP_FORMA_PAGO_PK ON EP_FORMA_PAGO
(ID);


ALTER TABLE EP_FORMA_PAGO ADD (
  CONSTRAINT EP_FORMA_PAGO_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_FORMA_PAGO ADD (
  CONSTRAINT FK_EP_FP_TIPPAG 
 FOREIGN KEY (TIP_FPAG) 
 REFERENCES TIPO_PAGO (ID_PAGO),
  CONSTRAINT FK_EP_ESTPRE 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));