CREATE TABLE EP_OBLIGACIONESC
(
  ID         NUMBER,
  ID_EP      NUMBER,
  DES_OBLIG  CLOB,
  GRUPO      NUMBER
);

COMMENT ON TABLE EP_OBLIGACIONESC IS 'LISTADO DE OBLIGACIONES DEL CONTRATISTA';

COMMENT ON COLUMN EP_OBLIGACIONESC.ID IS 'ID UNICO DE LA OBLIGACIÓN';

COMMENT ON COLUMN EP_OBLIGACIONESC.ID_EP IS 'REFERENCIA AL ESTPREV';

COMMENT ON COLUMN EP_OBLIGACIONESC.DES_OBLIG IS 'DESCRIPCION DE CADA OBLIGACIÓN';

COMMENT ON COLUMN EP_OBLIGACIONESC.GRUPO IS 'GRUPO AL CUAL PERTENECE';


CREATE UNIQUE INDEX EP_OBLIGACIONESC_PK ON EP_OBLIGACIONESC
(ID);

ALTER TABLE EP_OBLIGACIONESC ADD (
  CONSTRAINT EP_OBLIGACIONESC_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_OBLIGACIONESC ADD (
  CONSTRAINT EP_OBLIG_ESTPREV 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));
