CREATE TABLE EP_OBLIGACIONESE
(
  ID         NUMBER,
  ID_EP      NUMBER,
  DES_OBLIG  CLOB,
  GRUPO      NUMBER
);

COMMENT ON TABLE EP_OBLIGACIONESE IS 'LISTADO DE OBLIGACIONES DEL ENTIDAD';

COMMENT ON COLUMN EP_OBLIGACIONESE.ID IS 'ID UNICO DE LA OBLIGACIÓN ENTIDAD';

COMMENT ON COLUMN EP_OBLIGACIONESE.ID_EP IS 'REFERENCIA AL ESTPREV';

COMMENT ON COLUMN EP_OBLIGACIONESE.DES_OBLIG IS 'DESCRIPCION DE CADA OBLIGACIÓN';

COMMENT ON COLUMN EP_OBLIGACIONESE.GRUPO IS 'GRUPO AL CUAL PERTENECE';


CREATE UNIQUE INDEX EP_OBLIGACIONESE_PK ON EP_OBLIGACIONESE
(ID);


ALTER TABLE EP_OBLIGACIONESE ADD (
  CONSTRAINT EP_OBLIGACIONESE_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_OBLIGACIONESE ADD (
  CONSTRAINT EP_OBLIGE_ESTPREV 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));
