CREATE TABLE EP_POLIZAS
(
  ID             NUMBER,
  COD_POL        NUMBER(10),
  ID_EP          NUMBER,
  POR_SMMLV      NUMBER,
  CAL_APARTIRDE  VARCHAR2(3 BYTE),
  VIGENCIA       NUMBER,
  APARTIRDE      VARCHAR2(5 BYTE),
  TIPO           VARCHAR2(10 BYTE),
  GRUPO          NUMBER(10)
);

COMMENT ON TABLE EP_POLIZAS IS 'REGISTRO DE POLIZAS PARA EL ESTUDIO PREVIO';

COMMENT ON COLUMN EP_POLIZAS.ID IS 'ID DEL REGISTRO';

COMMENT ON COLUMN EP_POLIZAS.COD_POL IS 'CODIGO DE POLIZA';

COMMENT ON COLUMN EP_POLIZAS.ID_EP IS 'IDENTIFICADOR DEL EP';

COMMENT ON COLUMN EP_POLIZAS.POR_SMMLV IS 'PORCENTAJE O SMMLV';

COMMENT ON COLUMN EP_POLIZAS.VIGENCIA IS 'VIGENCIA ';

COMMENT ON COLUMN EP_POLIZAS.APARTIRDE IS 'APARTIR DE';

COMMENT ON COLUMN EP_POLIZAS.TIPO IS 'PORCENTAJE(%) O SALARIO MINIMO (SMML)';

COMMENT ON COLUMN EP_POLIZAS.GRUPO IS 'GRUPO';


CREATE UNIQUE INDEX EP_POLIZAS_PK ON EP_POLIZAS
(ID);


CREATE UNIQUE INDEX EP_POL_UNIK ON EP_POLIZAS
(COD_POL, ID_EP, GRUPO);


ALTER TABLE EP_POLIZAS ADD (
  CONSTRAINT EP_POLIZAS_PK
 PRIMARY KEY
 (ID),
  CONSTRAINT EP_POL_UNIK
 UNIQUE (COD_POL, ID_EP, GRUPO));

ALTER TABLE EP_POLIZAS ADD (
  CONSTRAINT EP_POL_CODPOL 
 FOREIGN KEY (COD_POL) 
 REFERENCES POLIZAS (COD_POL),
  CONSTRAINT EP_PO_CALPOL 
 FOREIGN KEY (CAL_APARTIRDE) 
 REFERENCES CALCULOPOL (COD_CAL),
  CONSTRAINT EP_POL_APARTIRDE 
 FOREIGN KEY (APARTIRDE) 
 REFERENCES CAL_VIG_POL (COD_CAL),
  CONSTRAINT EP_POLI_ESTPRE 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));
