CREATE TABLE EP_POLIZAS2
(
  ID       NUMBER,
  COD_POL  NUMBER(10),
  DES_POL  VARCHAR2(1000 BYTE),
  PLA_POL  VARCHAR2(10 BYTE),
  VAL_POL  VARCHAR2(10 BYTE),
  GRUPO    NUMBER(10),
  ID_EP    NUMBER
);

COMMENT ON TABLE EP_POLIZAS2 IS 'REGISTRO DE POLIZAS 2 VERSIÓN';

COMMENT ON COLUMN EP_POLIZAS2.ID IS 'ID UNICO';

COMMENT ON COLUMN EP_POLIZAS2.COD_POL IS 'CODIGO DE LA POLIZA';

COMMENT ON COLUMN EP_POLIZAS2.DES_POL IS 'DESCRIPCION DEL AMPARO';

COMMENT ON COLUMN EP_POLIZAS2.PLA_POL IS 'PLAZO DEL AMPARO';

COMMENT ON COLUMN EP_POLIZAS2.VAL_POL IS 'VALOR BASE DEL AMPARO';

COMMENT ON COLUMN EP_POLIZAS2.GRUPO IS 'GRUPO A CONTRATAR';

COMMENT ON COLUMN EP_POLIZAS2.ID_EP IS 'IDE DE ESTUDIO PREVIO';


ALTER TABLE EP_POLIZAS2 ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE EP_POLIZAS2 ADD (
  CONSTRAINT EP_POLIZAS2_POL 
 FOREIGN KEY (COD_POL) 
 REFERENCES POLIZAS (COD_POL),
  CONSTRAINT EP_POLIZAS2_IDEP 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));