CREATE TABLE EP_PROYECTOS
(
  ID_EP     NUMBER,
  COD_PRO   VARCHAR2(30 BYTE),
  FEC_REG   DATE,
  USAP_REG  VARCHAR2(12 BYTE),
  FEC_MOD   DATE,
  USAP_MOD  VARCHAR2(12 BYTE)
);


CREATE UNIQUE INDEX EP_PROYECTOS_PK ON EP_PROYECTOS
(ID_EP, COD_PRO);


ALTER TABLE EP_PROYECTOS ADD (
  CONSTRAINT EP_PROYECTOS_PK
 PRIMARY KEY
 (ID_EP, COD_PRO));

ALTER TABLE EP_PROYECTOS ADD (
  CONSTRAINT EP_PROY_PRY 
 FOREIGN KEY (COD_PRO) 
 REFERENCES PROYECTOS (PROYECTO),
  CONSTRAINT EP_PROY_EP 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));