CREATE TABLE EP_RUBROS_CDP
(
  ID         NUMBER,
  ID_EP      NUMBER,
  COD_RUB    VARCHAR2(50 BYTE),
  VALOR      NUMBER(17,2),
  NRO_CDP    VARCHAR2(20 BYTE),
  VIG_CDP    NUMBER(4),
  GRUPO      NUMBER(10),
  FEC_REG    DATE,
  USAP_REG   VARCHAR2(12 BYTE),
  FEC_MOD    DATE,
  USAP_MOD   VARCHAR2(12 BYTE),
  ID_EP_CDP  NUMBER
);

COMMENT ON TABLE EP_RUBROS_CDP IS 'EST PREV RUBROS CDP';

COMMENT ON COLUMN EP_RUBROS_CDP.ID IS 'ID UNICO';

COMMENT ON COLUMN EP_RUBROS_CDP.ID_EP IS 'ID DEL ESTUDIO PREVIO';

COMMENT ON COLUMN EP_RUBROS_CDP.COD_RUB IS 'CODIGO DEL RUBRO';

COMMENT ON COLUMN EP_RUBROS_CDP.VALOR IS 'VALOR DEL RUBRO PARA EL CONTRATO';

COMMENT ON COLUMN EP_RUBROS_CDP.NRO_CDP IS 'NRO DEL CDP';

COMMENT ON COLUMN EP_RUBROS_CDP.VIG_CDP IS 'VIGENCIA DEL CDP';

COMMENT ON COLUMN EP_RUBROS_CDP.GRUPO IS 'GRUPO';

COMMENT ON COLUMN EP_RUBROS_CDP.FEC_REG IS 'FECHA DEL REGISTRO';

COMMENT ON COLUMN EP_RUBROS_CDP.USAP_REG IS 'USUARIO QUE CREA EL REGISTRO';

COMMENT ON COLUMN EP_RUBROS_CDP.FEC_MOD IS 'FECHA DE MODIFIACION';

COMMENT ON COLUMN EP_RUBROS_CDP.USAP_MOD IS 'USUARIO DE ULTIMA MODIFICACIÓN';

COMMENT ON COLUMN EP_RUBROS_CDP.ID_EP_CDP IS 'ID DEL CDP';


CREATE UNIQUE INDEX EP_RUBROS_CDP_PK ON EP_RUBROS_CDP
(ID);


ALTER TABLE EP_RUBROS_CDP ADD (
  CONSTRAINT EP_RUBROS_CDP_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_RUBROS_CDP ADD (
  CONSTRAINT EP_RUBROS_CDP_R02 
 FOREIGN KEY (COD_RUB, VIG_CDP) 
 REFERENCES RUBROS (COD_RUB,VIGENCIA),
  CONSTRAINT EP_RUBROS_CDP_FK 
 FOREIGN KEY (ID_EP, NRO_CDP) 
 REFERENCES EP_CDP (ID_EP,NRO_CDP),
  FOREIGN KEY (ID_EP_CDP) 
 REFERENCES EP_CDP (ID));