CREATE TABLE PL_TIPOS_PLANTILLA
(
  COD_TIP  VARCHAR2(2 BYTE),
  NOM_TIP  VARCHAR2(20 BYTE)
);


CREATE UNIQUE INDEX PL_TIPOS_PLANTILLA_PK ON PL_TIPOS_PLANTILLA
(COD_TIP);


ALTER TABLE PL_TIPOS_PLANTILLA ADD (
  CONSTRAINT PL_TIPOS_PLANTILLA_PK
 PRIMARY KEY
 (COD_TIP));