CREATE TABLE MOD_TIP_PLA
(
  COD_MOD  VARCHAR2(5 BYTE),
  COD_TIP  VARCHAR2(2 BYTE),
  EST      VARCHAR2(2 BYTE)
);


CREATE UNIQUE INDEX MOD_TIP_PLA_PK ON MOD_TIP_PLA
(COD_MOD, COD_TIP);


ALTER TABLE MOD_TIP_PLA ADD (
  CONSTRAINT MOD_TIP_PLA_PK
 PRIMARY KEY
 (COD_MOD, COD_TIP));

ALTER TABLE MOD_TIP_PLA ADD (
  CONSTRAINT MOD_TIPPLA_FK 
 FOREIGN KEY (COD_MOD) 
 REFERENCES TIPOSPROC (COD_TPROC),
  CONSTRAINT TIP_TIPPLA_FK 
 FOREIGN KEY (COD_TIP) 
 REFERENCES PL_TIPOS_PLANTILLA (COD_TIP));