CREATE TABLE EP_CODIGOSUNSPSC
(
  UNSPSC        VARCHAR2(8 BYTE),
  CODIGO        VARCHAR2(8 BYTE),
  NOMBRE        VARCHAR2(300 BYTE),
  CLASIFICADOR  VARCHAR2(1 BYTE),
  PADRE         VARCHAR2(8 BYTE)
);

COMMENT ON TABLE EP_CODIGOSUNSPSC IS 'Base de Datos de Códigos UNSPSC';

COMMENT ON COLUMN EP_CODIGOSUNSPSC.UNSPSC IS 'Codigo Formateado';

COMMENT ON COLUMN EP_CODIGOSUNSPSC.CODIGO IS 'Código Sin Ceros a la Izquierda';

COMMENT ON COLUMN EP_CODIGOSUNSPSC.NOMBRE IS 'Nombre del B/S (Bien o Servicio)';

COMMENT ON COLUMN EP_CODIGOSUNSPSC.CLASIFICADOR IS 'Clasificador [Segmento, Familia, Clase, Producto]';

COMMENT ON COLUMN EP_CODIGOSUNSPSC.PADRE IS 'COdigo del Padre, Fk Misma Tabla';


CREATE UNIQUE INDEX EP_CODIGOSUNSPSC_PK ON EP_CODIGOSUNSPSC
(UNSPSC);


ALTER TABLE EP_CODIGOSUNSPSC ADD (
  CONSTRAINT EP_CODIGOSUNSPSC_PK
 PRIMARY KEY
 (UNSPSC));

ALTER TABLE EP_CODIGOSUNSPSC ADD (
  CONSTRAINT EP_CODIGOSUNSPSC_R01 
 FOREIGN KEY (PADRE) 
 REFERENCES EP_CODIGOSUNSPSC (UNSPSC));