CREATE TABLE EP_RIESGOS
(
  ID                  NUMBER,
  N                   NUMBER,
  ID_EP               NUMBER,
  CLASE               VARCHAR2(20 BYTE),
  FUENTE              VARCHAR2(10 BYTE),
  ETAPA               VARCHAR2(20 BYTE),
  TIPO                VARCHAR2(50 BYTE),
  DESCRIPCION         VARCHAR2(100 BYTE),
  CONSECUENCIAS       VARCHAR2(100 BYTE),
  PROBABILIDAD_R      NUMBER(1),
  IMPACTO_R           NUMBER(1),
  VALORACION_R        NUMBER(2),
  CATEGORIA_R         VARCHAR2(50 BYTE),
  AQUIENSEASIGNA      VARCHAR2(50 BYTE),
  TRATAMIENTO         VARCHAR2(100 BYTE),
  PROBABILIDAD_T      NUMBER(1),
  IMPACTO_T           NUMBER(1),
  VALORACION_T        NUMBER(2),
  CATEGORIA_T         VARCHAR2(50 BYTE),
  AFECTAEJECUCIONCTO  VARCHAR2(2 BYTE),
  RESPONSABLE         VARCHAR2(100 BYTE),
  FECHAINICIO         DATE,
  FECHACOMPLETA       DATE,
  FORMA_MONITOREO     VARCHAR2(100 BYTE),
  PERIOCIDAD          VARCHAR2(50 BYTE)
);

COMMENT ON TABLE EP_RIESGOS IS 'Items para L Matriz de Riesgos';

COMMENT ON COLUMN EP_RIESGOS.ID IS 'Id Unico';

COMMENT ON COLUMN EP_RIESGOS.N IS 'Id del Riesgo en el Estudio Previo';

COMMENT ON COLUMN EP_RIESGOS.ID_EP IS 'Id Estudio Previo';

COMMENT ON COLUMN EP_RIESGOS.CLASE IS 'Clase de Riesgo';

COMMENT ON COLUMN EP_RIESGOS.FUENTE IS 'Fuente del Riesgo (Interno, Externo)';

COMMENT ON COLUMN EP_RIESGOS.ETAPA IS 'Etapa del Proceso';

COMMENT ON COLUMN EP_RIESGOS.TIPO IS 'Tipo de Riesgo';

COMMENT ON COLUMN EP_RIESGOS.DESCRIPCION IS 'Descripción del Riesgo';

COMMENT ON COLUMN EP_RIESGOS.CONSECUENCIAS IS 'Consecuencias del Riesgo';

COMMENT ON COLUMN EP_RIESGOS.PROBABILIDAD_R IS 'Probabilidad del Riesgo';

COMMENT ON COLUMN EP_RIESGOS.IMPACTO_R IS 'Impacto del Riesgo';

COMMENT ON COLUMN EP_RIESGOS.VALORACION_R IS 'Valoración -> Impacto +  Probabilidad';

COMMENT ON COLUMN EP_RIESGOS.CATEGORIA_R IS 'Categoria';

COMMENT ON COLUMN EP_RIESGOS.AQUIENSEASIGNA IS 'A quien se asigna el riesgo';

COMMENT ON COLUMN EP_RIESGOS.TRATAMIENTO IS 'Tratamiento del riesgo';

COMMENT ON COLUMN EP_RIESGOS.PROBABILIDAD_T IS 'probabilidad posterior al tratamiento';

COMMENT ON COLUMN EP_RIESGOS.IMPACTO_T IS 'impactor posterior al tratamiento';

COMMENT ON COLUMN EP_RIESGOS.VALORACION_T IS 'valoración posterior al tratamiento';

COMMENT ON COLUMN EP_RIESGOS.CATEGORIA_T IS 'categoria posterior al tratamiento';

COMMENT ON COLUMN EP_RIESGOS.AFECTAEJECUCIONCTO IS 'afecta la ejecución del contrato (SI/NO)';

COMMENT ON COLUMN EP_RIESGOS.RESPONSABLE IS 'Responsable del Riesgo';

COMMENT ON COLUMN EP_RIESGOS.FECHAINICIO IS 'Fecha Estimada en que se inicia el tratamiento';

COMMENT ON COLUMN EP_RIESGOS.FECHACOMPLETA IS 'Fecha estimada en que se completa el tratamiento';

COMMENT ON COLUMN EP_RIESGOS.FORMA_MONITOREO IS '¿Cómo se Monitorea el Tratamiento?';

COMMENT ON COLUMN EP_RIESGOS.PERIOCIDAD IS 'Periodicidad ¿Cuándo?';


CREATE UNIQUE INDEX EP_RIESGOS_PK ON EP_RIESGOS
(ID);


ALTER TABLE EP_RIESGOS ADD (
  CONSTRAINT EP_RIESGOS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_RIESGOS ADD (
  CONSTRAINT EP_RIESGOS_FK_ESTPREV 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));