CREATE TABLE EP_UNSPSC
(
  ID      NUMBER,
  ID_EP   NUMBER,
  UNSPSC  VARCHAR2(8 BYTE)
);

COMMENT ON TABLE EP_UNSPSC IS 'Códigos CUPS, del Estudio Previo.';

COMMENT ON COLUMN EP_UNSPSC.ID IS 'Id Consecutivo';

COMMENT ON COLUMN EP_UNSPSC.ID_EP IS 'Id Estudio Previo';

COMMENT ON COLUMN EP_UNSPSC.UNSPSC IS 'Código Unspsc';


CREATE UNIQUE INDEX EP_UNSPSC_PK ON EP_UNSPSC
(ID);


ALTER TABLE EP_UNSPSC ADD (
  CONSTRAINT EP_UNSPSC_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_UNSPSC ADD (
  CONSTRAINT EP_UNSPSC_FK 
 FOREIGN KEY (UNSPSC) 
 REFERENCES EP_CODIGOSUNSPSC (UNSPSC),
  CONSTRAINT EP_UNSPSC_FK_EP 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));