CREATE TABLE PPROPONENTESS
(
  ID                NUMBER,
  TIPO_PROP         VARCHAR2(2 BYTE),
  NUM_PROC          VARCHAR2(20 BYTE),
  FEC_PROP          DATE,
  VAL_PROP          NUMBER(17,2),
  NUM_FOLIO         NUMBER,
  IDE_PROP          VARCHAR2(30 BYTE),
  TIP_IDE_PROP      CHAR(3 BYTE),
  EXP_IDE_PROP      VARCHAR2(50 BYTE),
  DV_PROP           VARCHAR2(1 BYTE),
  TIP_PER_PROP      VARCHAR2(10 BYTE),
  APE1_PROP         VARCHAR2(1000 BYTE),
  APE2_PROP         VARCHAR2(100 BYTE),
  NOM1_PROP         VARCHAR2(15 BYTE),
  NOM2_PROP         VARCHAR2(15 BYTE),
  RAZ_SOC           VARCHAR2(500 BYTE),
  DIR_PROP          VARCHAR2(50 BYTE),
  TEL_PROP          VARCHAR2(50 BYTE),
  EMA_PROP          VARCHAR2(50 BYTE),
  FEC_NAC           DATE,
  ADJUDICADO        VARCHAR2(1 BYTE)            DEFAULT 'N',
  FEC_ADJUDICACION  DATE,
  OBS_ADJUDICACION  VARCHAR2(300 CHAR),
  ESTADO            VARCHAR2(2 BYTE)            DEFAULT 'AC',
  COD_AUX           VARCHAR2(6 BYTE),
  ID_REP_LEGAL      VARCHAR2(20 BYTE),
  MUNICIPIO         VARCHAR2(100 BYTE),
  FEC_REG           DATE                        DEFAULT SYSDATE,
  USBD              VARCHAR2(20 BYTE),
  USAP              VARCHAR2(20 BYTE),
  FEC_MOD           DATE,
  USBD_MOD          VARCHAR2(20 BYTE),
  USAP_MOD          VARCHAR2(20 BYTE),
  APORTES           CLOB,
  NUMPOLIZA         VARCHAR2(20 BYTE),
  FECHA_INICIAL     DATE,
  FECHA_FINAL       DATE,
  ASEGURADORA       NUMBER(10),
  NOM_POLIZA        NUMBER(10)                  DEFAULT 61,
  VALOR_POLIZA      NUMBER(17,2),
  DENOMINACION      VARCHAR2(100 BYTE)          DEFAULT 'CONTRATISTA',
  VAL_SIN_IVA       NUMBER(17,2)
);

COMMENT ON TABLE PPROPONENTESS IS 'PROPONETES VERSION SIRCC4';

COMMENT ON COLUMN PPROPONENTESS.ID IS 'ID CONSECUTIVO';

COMMENT ON COLUMN PPROPONENTESS.TIPO_PROP IS 'TIPO PU, CS, UT';

COMMENT ON COLUMN PPROPONENTESS.NUM_PROC IS 'N° DEL PROCESO';

COMMENT ON COLUMN PPROPONENTESS.FEC_PROP IS 'FECHA DE ENTREGA DE PROPUESTA';

COMMENT ON COLUMN PPROPONENTESS.VAL_PROP IS 'VALOR DE LA PROPUSTA';

COMMENT ON COLUMN PPROPONENTESS.NUM_FOLIO IS 'N° DE FOLIOS PROPUESTA';

COMMENT ON COLUMN PPROPONENTESS.IDE_PROP IS 'IDENTIFICAICON';

COMMENT ON COLUMN PPROPONENTESS.TIP_IDE_PROP IS 'TIPO IDE';

COMMENT ON COLUMN PPROPONENTESS.EXP_IDE_PROP IS 'EXPEDIDA EN';

COMMENT ON COLUMN PPROPONENTESS.DV_PROP IS 'DIGITO DE VERIFICACION';

COMMENT ON COLUMN PPROPONENTESS.TIP_PER_PROP IS 'PERSONA JURIDICA / PERSONA NATURAL';

COMMENT ON COLUMN PPROPONENTESS.APE1_PROP IS 'APELLIDO1 DEL PROPONENTES';

COMMENT ON COLUMN PPROPONENTESS.APE2_PROP IS 'APELLIDO 2 DEL PROPONENTES';

COMMENT ON COLUMN PPROPONENTESS.NOM1_PROP IS 'NOMBRE 1 DEL PROPONENTES';

COMMENT ON COLUMN PPROPONENTESS.NOM2_PROP IS 'NOMBRE 2 DEL PROPONENTES';

COMMENT ON COLUMN PPROPONENTESS.RAZ_SOC IS 'RAZON SOCUAL';

COMMENT ON COLUMN PPROPONENTESS.DIR_PROP IS 'DIRECCION PROPONENTE';

COMMENT ON COLUMN PPROPONENTESS.TEL_PROP IS 'TELEFONO DEL PROPONENTE';

COMMENT ON COLUMN PPROPONENTESS.EMA_PROP IS 'EMAIL ';

COMMENT ON COLUMN PPROPONENTESS.FEC_NAC IS 'FECHA DE NACIMIENTO / CREACION';

COMMENT ON COLUMN PPROPONENTESS.ADJUDICADO IS 'ADJUDICADO?';

COMMENT ON COLUMN PPROPONENTESS.FEC_ADJUDICACION IS 'FECHA ADJUDICACION';

COMMENT ON COLUMN PPROPONENTESS.OBS_ADJUDICACION IS 'OBSERVACION';

COMMENT ON COLUMN PPROPONENTESS.ESTADO IS 'ESTADO';

COMMENT ON COLUMN PPROPONENTESS.COD_AUX IS 'COD AUX, CASOS DE UT Y CS';

COMMENT ON COLUMN PPROPONENTESS.ID_REP_LEGAL IS 'IDE TER DEL REPRESENTANTE LEGAL';

COMMENT ON COLUMN PPROPONENTESS.MUNICIPIO IS 'MUNICIPIO';

COMMENT ON COLUMN PPROPONENTESS.FEC_REG IS 'FECHA DE REGISTRO /CREACION';

COMMENT ON COLUMN PPROPONENTESS.USBD IS 'USUARIO DE LA BASE DE DATOS';

COMMENT ON COLUMN PPROPONENTESS.USAP IS 'USUARIO DE LA APLICACION';

COMMENT ON COLUMN PPROPONENTESS.FEC_MOD IS 'FECHA DE MODIFICACION';

COMMENT ON COLUMN PPROPONENTESS.USBD_MOD IS 'USUARIO DE LA BD Q MODIFICA ';

COMMENT ON COLUMN PPROPONENTESS.USAP_MOD IS 'USUARIO DE LA APP QUE MODIFICA';

COMMENT ON COLUMN PPROPONENTESS.APORTES IS 'EN QUE CONSISTEN LOS APORTES';

COMMENT ON COLUMN PPROPONENTESS.VAL_SIN_IVA IS 'VALOR SIN IVA';


CREATE UNIQUE INDEX PPROPONENTESS_PK ON PPROPONENTESS
(ID);


ALTER TABLE PPROPONENTESS ADD (
  CONSTRAINT PPROPONENTESS_PK
 PRIMARY KEY
 (ID));

ALTER TABLE PPROPONENTESS ADD (
  CONSTRAINT PPROPONENTESS_FK01 
 FOREIGN KEY (NUM_PROC) 
 REFERENCES PCONTRATOS (PRO_SEL_NRO),
  CONSTRAINT FKNPROPTIPO 
 FOREIGN KEY (TIPO_PROP) 
 REFERENCES TIPPROPONENTE (COD_TIPPROP),
  CONSTRAINT FKNTERCEROS 
 FOREIGN KEY (IDE_PROP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT FKNTERCEROS_RP 
 FOREIGN KEY (ID_REP_LEGAL) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT PPROPONENTESS_FK_ASEG 
 FOREIGN KEY (ASEGURADORA) 
 REFERENCES ASEGURADORAS (COD_ASE),
  CONSTRAINT PPROPONENTESS_FK_POL 
 FOREIGN KEY (NOM_POLIZA) 
 REFERENCES POLIZAS (COD_POL));