CREATE TABLE DT_PARAMETROS
(
  ID           NUMBER,
  NOMBRE       VARCHAR2(100 BYTE),
  VALOR        VARCHAR2(100 BYTE),
  DESCRIPCION  VARCHAR2(200 BYTE)
);

COMMENT ON TABLE DT_PARAMETROS IS 'TABLA DE PARAMETROS DE LA APLICACIÓN';

COMMENT ON COLUMN DT_PARAMETROS.ID IS 'ID UNICO';

COMMENT ON COLUMN DT_PARAMETROS.NOMBRE IS 'NOMBRE DEL PARAMETRO';

COMMENT ON COLUMN DT_PARAMETROS.VALOR IS 'VALOR DEL PARAMETRO';

COMMENT ON COLUMN DT_PARAMETROS.DESCRIPCION IS 'DESCRIPCIÓN BREVE DEL PARAMETRO';


CREATE UNIQUE INDEX DT_PARAMETROS_PK ON DT_PARAMETROS
(ID);


ALTER TABLE DT_PARAMETROS ADD (
  CONSTRAINT DT_PARAMETROS_PK
 PRIMARY KEY
 (ID));