CREATE TABLE PL_PLANTILLA
(
  ID       NUMBER,
  COD_TIP  VARCHAR2(2 BYTE),
  TITULO   VARCHAR2(50 BYTE),
  FEC_REV  DATE,
  NRO_REV  VARCHAR2(20 BYTE),
  EST_PLA  VARCHAR2(2 BYTE),
  DOC_MAX  NUMBER
);

COMMENT ON TABLE PL_PLANTILLA IS 'PL PLANTILLAS';

COMMENT ON COLUMN PL_PLANTILLA.ID IS 'ID UNICO';

COMMENT ON COLUMN PL_PLANTILLA.COD_TIP IS 'CODIGO DEL TIPO';

COMMENT ON COLUMN PL_PLANTILLA.TITULO IS 'TITULO  DEL DOCUMENTO';

COMMENT ON COLUMN PL_PLANTILLA.FEC_REV IS 'FECHA DE REVISION';

COMMENT ON COLUMN PL_PLANTILLA.NRO_REV IS 'NRO DE REVISION';

COMMENT ON COLUMN PL_PLANTILLA.EST_PLA IS 'ESTADO DE LA PLANTILLA';

COMMENT ON COLUMN PL_PLANTILLA.DOC_MAX IS 'MAXIMO DOCUMENTO';


CREATE UNIQUE INDEX PL_PLANTILLA_PK ON PL_PLANTILLA
(ID);


ALTER TABLE PL_PLANTILLA ADD (
  CONSTRAINT PL_PLANTILLA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE PL_PLANTILLA ADD (
  CONSTRAINT PL_PLANTILLA_TIP_FK 
 FOREIGN KEY (COD_TIP) 
 REFERENCES PL_TIPOS_PLANTILLA (COD_TIP));