CREATE TABLE DOC_PLANTILLA
(
  ID        NUMBER,
  NRO_DOC   VARCHAR2(20 BYTE),
  COD_TIP   VARCHAR2(2 BYTE),
  TITULO    VARCHAR2(50 BYTE),
  FEC_REV   DATE,
  NRO_REV   VARCHAR2(20 BYTE),
  EST_DOC   VARCHAR2(2 BYTE),
  FEC_DOC   DATE,
  NUM_PROC  VARCHAR2(20 BYTE),
  ID_PLA    NUMBER
);

COMMENT ON TABLE DOC_PLANTILLA IS 'DOCUMENTOS';

COMMENT ON COLUMN DOC_PLANTILLA.ID IS 'ID DEL DOCUMENTO';

COMMENT ON COLUMN DOC_PLANTILLA.NRO_DOC IS 'NRO DOCUMENTO';

COMMENT ON COLUMN DOC_PLANTILLA.COD_TIP IS 'CODIGO DEL TIPO';

COMMENT ON COLUMN DOC_PLANTILLA.TITULO IS 'TITULO DEL DOCUMENTO';

COMMENT ON COLUMN DOC_PLANTILLA.FEC_REV IS 'FECHA DE REVISION';

COMMENT ON COLUMN DOC_PLANTILLA.NRO_REV IS 'NRO DE REVISION';

COMMENT ON COLUMN DOC_PLANTILLA.EST_DOC IS 'ESTADO  DE LA PLANTILLA';

COMMENT ON COLUMN DOC_PLANTILLA.NUM_PROC IS 'NUMERO DE PROCESO';


CREATE UNIQUE INDEX DOC_PLANTILLA_PK ON DOC_PLANTILLA
(ID);


ALTER TABLE DOC_PLANTILLA ADD (
  CONSTRAINT DOC_PLANTILLA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE DOC_PLANTILLA ADD (
  CONSTRAINT DOC_PLANTILLA_TIP_FK 
 FOREIGN KEY (COD_TIP) 
 REFERENCES PL_TIPOS_PLANTILLA (COD_TIP),
  CONSTRAINT DOC_PLANTILLLA_PCON_FK 
 FOREIGN KEY (NUM_PROC) 
 REFERENCES PCONTRATOS (PRO_SEL_NRO),
  CONSTRAINT FK_DOC_PLA 
 FOREIGN KEY (ID_PLA) 
 REFERENCES PL_PLANTILLA (ID));