CREATE TABLE PL_SECCIONES
(
  ID      NUMBER,
  ID_PLA  NUMBER,
  HTML    CLOB
);

COMMENT ON TABLE PL_SECCIONES IS 'SECCIONES DEL DOCUMENTO DE LA PLANTILLAS ASOCIADO';

COMMENT ON COLUMN PL_SECCIONES.ID IS 'IDE UNICO';

COMMENT ON COLUMN PL_SECCIONES.ID_PLA IS 'ID DE PLANTILLAS';

COMMENT ON COLUMN PL_SECCIONES.HTML IS 'TEXTO HTML POR SECCION';


CREATE UNIQUE INDEX PL_SECCIONES_PK ON PL_SECCIONES
(ID);


ALTER TABLE PL_SECCIONES ADD (
  CONSTRAINT PL_SECCIONES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE PL_SECCIONES ADD (
  CONSTRAINT PL_SECCIONES_FK 
 FOREIGN KEY (ID_PLA) 
 REFERENCES PL_PLANTILLA (ID));