CREATE TABLE DOC_SECCIONES
(
  ID       NUMBER,
  ID_DOC   NUMBER,
  HTML     CLOB,
  CRUZADO  CLOB
);

COMMENT ON TABLE DOC_SECCIONES IS 'SECCIONES DE DOCUMENTOS';

COMMENT ON COLUMN DOC_SECCIONES.ID IS 'ID UNICO';

COMMENT ON COLUMN DOC_SECCIONES.ID_DOC IS 'ID UNICO DEL DOCUMENTO';


CREATE UNIQUE INDEX DOC_SECCIONES_PK ON DOC_SECCIONES
(ID);


ALTER TABLE DOC_SECCIONES ADD (
  CONSTRAINT DOC_SECCIONES_PK
 PRIMARY KEY
 (ID));

ALTER TABLE DOC_SECCIONES ADD (
  CONSTRAINT DOC_SECCIONES_FK 
 FOREIGN KEY (ID_DOC) 
 REFERENCES DOC_PLANTILLA (ID));