ALTER TABLE CONS_PROC ADD
(
    VIGENCIA2 NUMBER(4)
);

UPDATE CONS_PROC SET VIGENCIA2 = VIGENCIA;

COMMIT;

ALTER TABLE CONS_PROC DROP CONSTRAINT CONS_PROC_PK;

ALTER TABLE CONS_PROC DROP COLUMN VIGENCIA;

ALTER TABLE CONS_PROC RENAME COLUMN VIGENCIA2 TO VIGENCIA;

ALTER TABLE CONS_PROC ADD (CONSTRAINT CONS_PROC_PK PRIMARY KEY (VIGENCIA, DEP_DEL, TIP_PROC));