ALTER TABLE CONSORCIOSUTXC
 ADD (ID  NUMBER);

ALTER TABLE CONSORCIOSUTXC
 ADD (ID_PROP  NUMBER);


COMMENT ON TABLE CONSORCIOSUTXC IS 'CONSORCIOS';

COMMENT ON COLUMN CONSORCIOSUTXC.IDE_TER IS 'IDE DEL TERCERO';

COMMENT ON COLUMN CONSORCIOSUTXC.ID_MIEMBROS IS 'IDE DEL MIEMBRO';

COMMENT ON COLUMN CONSORCIOSUTXC.ID_ESTADO IS 'ESTADO';

COMMENT ON COLUMN CONSORCIOSUTXC.FEC_REG IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN CONSORCIOSUTXC.USBD IS 'USUARIO DE LA BASE DE DATO';

COMMENT ON COLUMN CONSORCIOSUTXC.USAP IS 'USUARIO DE LA APP';

COMMENT ON COLUMN CONSORCIOSUTXC.ID IS 'ID CONSECUTIVO';

COMMENT ON COLUMN CONSORCIOSUTXC.ID_PROP IS 'IDE DEL PROPONENTE';

Declare 
i number:=1;
Begin
    
   For rg in (Select * From CONSORCIOSUTXC Order by Fec_Reg )
   Loop
       Update CONSORCIOSUTXC c Set Id=i Where  c.ID_MIEMBROS=rg.ID_MIEMBROS And c.FEC_REG=rg.FEC_REG;
       i:=i+1;
   End Loop;
   Commit; 
End;

ALTER TABLE CONSORCIOSUTXC
 ADD CONSTRAINT CONSORCIOSUTXC_PK
 PRIMARY KEY
 (ID);

ALTER TABLE CONSORCIOSUTXC
 ADD CONSTRAINT CONSORCIOSUTXC_TER 
 FOREIGN KEY (IDE_TER) 
 REFERENCES TERCEROS (IDE_TER);

ALTER TABLE CONSORCIOSUTXC
 ADD CONSTRAINT CONSORCIOSUTXC_MIEM 
 FOREIGN KEY (ID_MIEMBROS) 
 REFERENCES TERCEROS (IDE_TER);

ALTER TABLE CONSORCIOSUTXC
 ADD CONSTRAINT CONSORCIOSUTXC_CTO 
 FOREIGN KEY (COD_CON) 
 REFERENCES CONTRATOS (COD_CON);

ALTER TABLE CONSORCIOSUTXC
 ADD CONSTRAINT CONSORCIOSUTXC_PROP 
 FOREIGN KEY (ID_PROP) 
 REFERENCES PPROPONENTESS (ID);

