CREATE TABLE C_POLIZAS2
(
  ID       NUMBER,
  COD_POL  NUMBER(10),
  DES_POL  VARCHAR2(1000 BYTE),
  PLA_POL  VARCHAR2(10 BYTE),
  VAL_POL  VARCHAR2(10 BYTE),
  GRUPO    NUMBER(10),
  COD_CON  VARCHAR2(10 BYTE)
)
;

COMMENT ON TABLE C_POLIZAS2 IS 'REGISTRO DE POLIZAS 2 VERSIÓN';

COMMENT ON COLUMN C_POLIZAS2.ID IS 'ID UNICO';

COMMENT ON COLUMN C_POLIZAS2.COD_POL IS 'CODIGO DE LA POLIZA';

COMMENT ON COLUMN C_POLIZAS2.DES_POL IS 'DESCRIPCION DEL AMPARO';

COMMENT ON COLUMN C_POLIZAS2.PLA_POL IS 'PLAZO DEL AMPARO';

COMMENT ON COLUMN C_POLIZAS2.VAL_POL IS 'VALOR BASE DEL AMPARO';

COMMENT ON COLUMN C_POLIZAS2.GRUPO IS 'GRUPO A CONTRATAR';

COMMENT ON COLUMN C_POLIZAS2.COD_CON IS 'IDE DE ESTUDIO PREVIO';


-- 
-- Non Foreign Key Constraints for Table C_POLIZAS2 
-- 
ALTER TABLE C_POLIZAS2 ADD (
  PRIMARY KEY
 (ID));

-- 
-- Foreign Key Constraints for Table C_POLIZAS2 
-- 
ALTER TABLE C_POLIZAS2 ADD (
  CONSTRAINT C_POLIZAS2_POL 
 FOREIGN KEY (COD_POL) 
 REFERENCES POLIZAS (COD_POL),
  CONSTRAINT C_POLIZAS2_CC 
 FOREIGN KEY (COD_CON) 
 REFERENCES CONTRATOS (COD_CON));