CREATE TABLE C_RUBROS_CDP
(
  ID         NUMBER,
  NRO_CDP    VARCHAR2(20 BYTE),  
  COD_RUB    VARCHAR2(50 BYTE),
  VALOR      NUMBER(17,2),  
  VIG_CDP    NUMBER(4),
  COD_CON    VARCHAR2(15),
  FEC_REG    DATE,
  USAP_REG   VARCHAR2(12 BYTE),
  FEC_MOD    DATE,
  USAP_MOD   VARCHAR2(12 BYTE) 
);

ALTER TABLE C_RUBROS_CDP
 ADD CONSTRAINT RUBROS_CDP_C_PK
 PRIMARY KEY
 (ID);


COMMENT ON TABLE C_RUBROS_CDP IS 'CONTRATOS RUBROS X CDP'
/

COMMENT ON COLUMN C_RUBROS_CDP.ID IS 'ID CONSECUTIVO'
/

COMMENT ON COLUMN C_RUBROS_CDP.NRO_CDP IS 'NRO DE CDP'
/

COMMENT ON COLUMN C_RUBROS_CDP.COD_RUB IS 'CODIGO RUBRO'
/

COMMENT ON COLUMN C_RUBROS_CDP.VALOR IS 'VALOR '
/

COMMENT ON COLUMN C_RUBROS_CDP.VIG_CDP IS 'VIGENCIA'
/

COMMENT ON COLUMN C_RUBROS_CDP.COD_CON IS 'CODIGO DEL CONTRATO'
/

COMMENT ON COLUMN C_RUBROS_CDP.FEC_REG IS 'FECHA DE REGISTRO'
/

COMMENT ON COLUMN C_RUBROS_CDP.USAP_REG IS 'USUARIO QUE REGISTRA'
/

COMMENT ON COLUMN C_RUBROS_CDP.FEC_MOD IS 'FECHA DE MODIFICACIÓN'
/

COMMENT ON COLUMN C_RUBROS_CDP.USAP_MOD IS 'USUARIO QUE MODIFICA'
/

ALTER TABLE C_RUBROS_CDP
 ADD CONSTRAINT C_RUBROS_CDP_FKCDP 
 FOREIGN KEY (NRO_CDP, COD_CON) 
 REFERENCES CDP_CONTRATOS (NRO_CDP, COD_CON);