ALTER TABLE IMPUESTOS ADD
(
    NRO_IMP2 VARCHAR2(10 BYTE)
);

UPDATE IMPUESTOS SET NRO_IMP2 = NRO_IMP;

COMMIT;

ALTER TABLE IMPUESTOS DROP CONSTRAINT IMPUESTOS_PK;

ALTER TABLE IMPUESTOS DROP COLUMN NRO_IMP;

ALTER TABLE IMPUESTOS RENAME COLUMN NRO_IMP2 TO NRO_IMP;

ALTER TABLE IMPUESTOS ADD (CONSTRAINT IMPUESTOS_PK PRIMARY KEY (NRO_IMP));