CREATE TABLE EP_PAA
(
  ID               NUMBER(10),
  VIGENCIA         NUMBER(4),
  DESCRIPCION      VARCHAR2(400 BYTE),
  FEC_EST_INI      DATE,
  PLA1_EJE         NUMBER,
  TIP1_PLA         VARCHAR2(10 BYTE),
  PLA2_EJE         NUMBER,
  TIP2_PLA         VARCHAR2(10 BYTE),
  MOD_SEL          VARCHAR2(10 BYTE),
  FUE_SEL          VARCHAR2(2 BYTE),
  VAL_TOT_EST      NUMBER(17,2),
  VAL_VIG_EST      NUMBER(17,2),
  VIG_FUT          VARCHAR2(2 BYTE),
  EST_SOL_VF       VARCHAR2(2 BYTE),
  DAT_RESPONSABLE  VARCHAR2(200 BYTE),
  COD_DEP          VARCHAR2(2 BYTE),
  ID_EP_MPAA       NUMBER
);

COMMENT ON COLUMN EP_PAA.ID_EP_MPAA IS 'ID DEL PADRE DEL PAA';


CREATE UNIQUE INDEX EP_PAA_PK ON EP_PAA
(ID);


ALTER TABLE EP_PAA ADD (
  CONSTRAINT EP_PAA_PK
 PRIMARY KEY
 (ID));

ALTER TABLE EP_PAA ADD (
  CONSTRAINT PAA_DEP_CON_FK 
 FOREIGN KEY (COD_DEP) 
 REFERENCES DEPENDENCIA (COD_DEP),
  CONSTRAINT EP_PAA_R02 
 FOREIGN KEY (ID_EP_MPAA) 
 REFERENCES EP_MPAA (ID));
