ALTER TABLE CONTRATOS RENAME CONSTRAINT CONTRATOS_R01 TO CONT_FK_TER;

ALTER TABLE CONTRATOS DROP CONSTRAINT CONTRATOS_LLAVEPRIMARIA CASCADE;

ALTER TABLE CONTRATOS DROP CONSTRAINT CODIGO CASCADE;

ALTER TABLE CONTRATOS ADD (
  CONSTRAINT CODIGO
 PRIMARY KEY
 (COD_CON));