ALTER TABLE PSOLICITUDES ADD CONSTRAINT PSOL_SUBT_FK 
 FOREIGN KEY (STIP_CON) 
 REFERENCES SUBTIPOS (COD_STIP);
 
 ALTER TABLE PSOLICITUDES ADD (
  CONSTRAINT PSOL_TIPOSCONT 
 FOREIGN KEY (TIP_CON) 
 REFERENCES TIPOSCONT (COD_TIP));

 UPDATE PSOLICITUDES SET IDE_CON = NULL WHERE IDE_CON NOT IN (SELECT IDE_TER FROM TERCEROS);
 COMMIT;

ALTER TABLE PSOLICITUDES ADD (
  CONSTRAINT PSOLICITUDES_TER 
 FOREIGN KEY (IDE_CON) 
 REFERENCES TERCEROS (IDE_TER));