CREATE TABLE PCLAUSULAS
(
  ID              NUMBER,
  ID_PLA          NUMBER,
  TIP_PLA         VARCHAR2(4 BYTE),
  CLA_TIT         VARCHAR2(200 BYTE),
  CLA_NUM         NUMBER,
  CLA_CAM         VARCHAR2(200 BYTE),
  CLA_PAR         VARCHAR2(200 BYTE),
  CLA_TEXTO       VARCHAR2(4000 BYTE),
  NUM_PRO         VARCHAR2(20 BYTE),
  IDE_PMIN        NUMBER,
  TIP_PAR         VARCHAR2(2 BYTE),
  IS_ENTER_FINAL  VARCHAR2(1 BYTE),
  ORDEN           NUMBER(2),
  CLA_CRUZADA     CLOB
);

COMMENT ON TABLE PCLAUSULAS IS 'COFIGURACION CLAUSULAS DE CONTRATOS';

COMMENT ON COLUMN PCLAUSULAS.ID IS 'ID UNICO';

COMMENT ON COLUMN PCLAUSULAS.ID_PLA IS 'ID A PLANTILLA A LA QUE PERTENECE';

COMMENT ON COLUMN PCLAUSULAS.TIP_PLA IS 'TIPO DE PLANTILLA';

COMMENT ON COLUMN PCLAUSULAS.CLA_TIT IS 'TITULO DE LA CLAUSULA';

COMMENT ON COLUMN PCLAUSULAS.CLA_NUM IS 'NÚMERO DE LA CLAUSULA';

COMMENT ON COLUMN PCLAUSULAS.CLA_CAM IS 'CAMPOS RELACIONADOS';

COMMENT ON COLUMN PCLAUSULAS.CLA_PAR IS 'PARRAGRAFOS ASOCIADOS';

COMMENT ON COLUMN PCLAUSULAS.CLA_TEXTO IS 'TEXTO DE LA CLAUSULA';

COMMENT ON COLUMN PCLAUSULAS.NUM_PRO IS 'NUMERO DE PROCESO';

COMMENT ON COLUMN PCLAUSULAS.TIP_PAR IS 'TIPO DE PARRAFO';

COMMENT ON COLUMN PCLAUSULAS.ORDEN IS 'ORDEN DE IMPRESION';

COMMENT ON COLUMN PCLAUSULAS.CLA_CRUZADA IS 'DATOS CRUZADOS';


CREATE UNIQUE INDEX PCLAUSULAS_PK ON PCLAUSULAS
(ID);


ALTER TABLE PCLAUSULAS ADD (
  CONSTRAINT PCLAUSULAS_PK
 PRIMARY KEY
 (ID));
