--- Se borra temporalmente mientra se averigua cual es el real
--- DELETE FROM CESIONES WHERE COD_CON = '2013021096' AND NIT_ANT = '42490379' AND NIT_NUE = '52382094';
--- COMMIT;

ALTER TABLE CESIONES ADD CONSTRAINT CESIONES_PK PRIMARY KEY (COD_CON, NIT_ANT, NIT_NUE);