CREATE TABLE ESTPREV
(
  ID                       NUMBER,
  OBJE_EP                  VARCHAR2(2000 BYTE),
  PLAZ1_EP                 NUMBER,
  TPLA1_EP                 CHAR(1 BYTE),
  PLAZ2_EP                 NUMBER,
  TPLA2_EP                 CHAR(1 BYTE),
  LUGE_EP                  VARCHAR2(300 BYTE),
  PLIQ_EP                  NUMBER,
  VAL_ENT_EP               NUMBER(17,2),
  VAL_OTR_EP               NUMBER(17,2),
  IDE_DIL_EP               VARCHAR2(12 BYTE),
  DEP_NEC_EP               VARCHAR2(2 BYTE),
  STIP_CON_EP              VARCHAR2(5 BYTE),
  FEC_ELA_EP               DATE,
  FEC_REG_EP               DATE,
  FEC_MOD_EP               DATE,
  USAP_REG_EP              VARCHAR2(12 BYTE),
  USAP_MOD_EP              VARCHAR2(12 BYTE),
  FEC_REV_EP               DATE,
  USAP_REV_EP              VARCHAR2(12 BYTE),
  USAP_ELA_EP              VARCHAR2(12 BYTE),
  FEC_ELAS_EP              DATE,
  USAP_APR_EP              VARCHAR2(12 BYTE),
  FEC_APR_EP               DATE,
  USAP_ANU_EP              VARCHAR2(12 BYTE),
  FEC_ANU_EP               DATE,
  USAP_DAN_EP              VARCHAR2(12 BYTE),
  FEC_DAN_EP               DATE,
  DEP_SUP_EP               VARCHAR2(2 BYTE),
  VIG_EP                   VARCHAR2(4 BYTE),
  CODIGO_EP                VARCHAR2(10 BYTE),
  GRUPOS_EP                NUMBER,
  NUM_EMP_EP               NUMBER,
  IDE_RES_EP               VARCHAR2(12 BYTE),
  MOD_SEL_EP               VARCHAR2(4 BYTE),
  NRO_EP                   NUMBER,
  EST_EP                   VARCHAR2(2 BYTE),
  EST_FLU_EP               VARCHAR2(2 BYTE),
  ES_PLAN_EP               VARCHAR2(1 BYTE),
  DEP_DEL_EP               VARCHAR2(2 BYTE),
  ENPLANC_EP               VARCHAR2(2 BYTE),
  NOM_PLA_EP               VARCHAR2(100 BYTE),
  ID_REV                   NUMBER,
  ID_APR                   NUMBER,
  OBLIGC                   CLOB,
  OBLIGE                   CLOB,
  PERSONA_APOYO            VARCHAR2(2 BYTE),
  ANTI_PORC                NUMBER(17,2),
  TIPO_FP                  VARCHAR2(2 BYTE),
  IDE_CON_EP               VARCHAR2(12 BYTE),
  IDE_REP_EP               VARCHAR2(12 BYTE),
  NEC_EP                   CLOB,
  OBLIGGRC                 CLOB,
  OBLIGGRE                 CLOB,
  JUST_VALOR_EP            CLOB,
  CAP_JURIDICA_EP          CLOB,
  CAP_FINANCIERA_EP        CLOB,
  CAP_RESIDUAL_EP          CLOB,
  PERS_LEGAL_EP            CLOB,
  PERS_ORGA_EP             CLOB,
  CAP_EXPERIENCA_EP        CLOB,
  NEC_CONT_INT_EP          CLOB,
  SOM_ACUE_COMER_EP        CLOB,
  CONST_CUMP_DEBERES_EP    CLOB,
  IDE_SUP_EP               VARCHAR2(12 BYTE),
  CAR_SUP_EP               VARCHAR2(100 BYTE),
  COD_UNSPSC_EP            VARCHAR2(100 BYTE),
  DES_UNSPSC_EP            VARCHAR2(2000 BYTE),
  ESP_OBJ_EP               CLOB,
  AUTPERLIC_EP             CLOB,
  DOCTECNICOS_EP           CLOB,
  VARIABLESPPTO_EP         CLOB,
  IDONEIDAD_EP             CLOB,
  CAP_ORGANIZACIONAL_EP    CLOB,
  FACTORES_EVALUACION_EP   CLOB,
  REGLAS_DESEMPATE_EP      CLOB,
  TIPO_PPTO                VARCHAR2(1 BYTE),
  PAAID                    NUMBER(10),
  PAADESC                  VARCHAR2(400 BYTE),
  FUN_JUR_MOD              CLOB,
  CONSIDERACIONES_EP       CLOB,
  ACT_CONT_EP              CLOB,
  DESC_APORTES_PROPIOS_EP  CLOB,
  REQ_CDP_EP               VARCHAR2(1 BYTE),
  OBS_CDP_EP               CLOB,
  OBS_POL_EP               CLOB,
  REQ_POL_EP               VARCHAR2(1 BYTE),
  INICIO_APARTIR_DE_EP     VARCHAR2(3 BYTE),
  FEC_INICIO_EP            DATE,
  FEC_FIN_EP               DATE,
  FEC_SUS_EP               DATE,
  CAR_RES_EP               VARCHAR2(12 BYTE)
);

COMMENT ON TABLE ESTPREV IS 'ESTUDIOS PREVIOS';

COMMENT ON COLUMN ESTPREV.IDONEIDAD_EP IS 'Idoneidad';

COMMENT ON COLUMN ESTPREV.CAP_ORGANIZACIONAL_EP IS 'Capacidad Organización';

COMMENT ON COLUMN ESTPREV.FACTORES_EVALUACION_EP IS 'Factores de Evaluación';

COMMENT ON COLUMN ESTPREV.REGLAS_DESEMPATE_EP IS 'Reglas de Desempate';

COMMENT ON COLUMN ESTPREV.TIPO_PPTO IS 'Tipo de Presupuesto (I-Inversión, F-Funcionamiento)';

COMMENT ON COLUMN ESTPREV.PAAID IS 'Descricpion del PAA';

COMMENT ON COLUMN ESTPREV.FUN_JUR_MOD IS 'Fundamentos Juridicos de La Modalidad';

COMMENT ON COLUMN ESTPREV.ACT_CONT_EP IS 'Actividades concretas a desarrollar ';

COMMENT ON COLUMN ESTPREV.DESC_APORTES_PROPIOS_EP IS 'Aportes Propios (Caso de Convenios)';

COMMENT ON COLUMN ESTPREV.REQ_CDP_EP IS 'Requiere CDP';

COMMENT ON COLUMN ESTPREV.OBS_CDP_EP IS 'Observaciones a CDP';

COMMENT ON COLUMN ESTPREV.CONSIDERACIONES_EP IS 'Consideraciones';

COMMENT ON COLUMN ESTPREV.OBS_POL_EP IS 'Observaciones a Pólizas';

COMMENT ON COLUMN ESTPREV.REQ_POL_EP IS 'Requiere Pólizas';

COMMENT ON COLUMN ESTPREV.INICIO_APARTIR_DE_EP IS 'Inicio Apartir de ';

COMMENT ON COLUMN ESTPREV.FEC_INICIO_EP IS 'Fecha de Inicio del Contrato ';

COMMENT ON COLUMN ESTPREV.FEC_FIN_EP IS 'Fecha de Terminación del Contrato ';

COMMENT ON COLUMN ESTPREV.FEC_SUS_EP IS 'Fecha de Suscripción del Contrato';

COMMENT ON COLUMN ESTPREV.CAP_FINANCIERA_EP IS 'Capacidad Financiera';

COMMENT ON COLUMN ESTPREV.NEC_EP IS 'Necesidad ';

COMMENT ON COLUMN ESTPREV.OBLIGGRC IS 'Obligaciones Generales del Contratista ';

COMMENT ON COLUMN ESTPREV.OBLIGGRE IS 'Obligaciones Generales del Contrantate';

COMMENT ON COLUMN ESTPREV.JUST_VALOR_EP IS 'Justificación del Valor del Contrato';

COMMENT ON COLUMN ESTPREV.CAP_JURIDICA_EP IS 'Capacidad Juridica';

COMMENT ON COLUMN ESTPREV.DEP_NEC_EP IS 'Dependencia quien Realiza el EP';

COMMENT ON COLUMN ESTPREV.STIP_CON_EP IS 'SubTipo/Clase de Contrato';

COMMENT ON COLUMN ESTPREV.FEC_ELA_EP IS 'Fecha de Elaboración del EP';

COMMENT ON COLUMN ESTPREV.FEC_REG_EP IS 'Fecha de Creación del Registro';

COMMENT ON COLUMN ESTPREV.FEC_MOD_EP IS 'Fecha de Ultima Modificación';

COMMENT ON COLUMN ESTPREV.USAP_REG_EP IS 'Usuario quien registra el estudio previo';

COMMENT ON COLUMN ESTPREV.USAP_MOD_EP IS 'Usuario quién modifico por ultima vez el estudio previo';

COMMENT ON COLUMN ESTPREV.FEC_REV_EP IS 'Fecha de Revisón del Estudio Previo';

COMMENT ON COLUMN ESTPREV.USAP_REV_EP IS 'Usuario quien revisa el estudio previo';

COMMENT ON COLUMN ESTPREV.USAP_ELA_EP IS 'Usuario quien Cambia a Estado Elaborado';

COMMENT ON COLUMN ESTPREV.FEC_ELAS_EP IS 'Fecha en que el EP pasa a Elaborado en el sistema';

COMMENT ON COLUMN ESTPREV.USAP_APR_EP IS 'usuario quien aprueba el estudio previo';

COMMENT ON COLUMN ESTPREV.FEC_APR_EP IS 'Fecha de Aprobado del Estudio Previo';

COMMENT ON COLUMN ESTPREV.USAP_ANU_EP IS 'Usuario quien Anula el Estudio Previo';

COMMENT ON COLUMN ESTPREV.FEC_ANU_EP IS 'Fecha en que se anula el estudio previo';

COMMENT ON COLUMN ESTPREV.USAP_DAN_EP IS 'Usuario desanula el estudio previo';

COMMENT ON COLUMN ESTPREV.FEC_DAN_EP IS 'FECHA DE DESANULAR EL EP';

COMMENT ON COLUMN ESTPREV.DEP_SUP_EP IS 'Dependencia quién desarrollará la supervisión';

COMMENT ON COLUMN ESTPREV.VIG_EP IS 'VIGENCIA DE ESTUDIO PREVIO';

COMMENT ON COLUMN ESTPREV.CODIGO_EP IS 'Código del Estudio Previo';

COMMENT ON COLUMN ESTPREV.GRUPOS_EP IS 'CANTIDAD DE GRUPOS EN EL ESTUDIO PREVIO';

COMMENT ON COLUMN ESTPREV.NUM_EMP_EP IS 'NUMERO DE EMPLEOS EN EL ESTUDIO PREVIO';

COMMENT ON COLUMN ESTPREV.IDE_RES_EP IS 'Ide del Responsable del Estudio Previo';

COMMENT ON COLUMN ESTPREV.MOD_SEL_EP IS 'Modalidad de Selección - Tipo de Proceso';

COMMENT ON COLUMN ESTPREV.NRO_EP IS 'Número x Vigencia del Estudio Previo';

COMMENT ON COLUMN ESTPREV.EST_EP IS 'Estado del EP';

COMMENT ON COLUMN ESTPREV.EST_FLU_EP IS 'ESTADO DEL FLUJO';

COMMENT ON COLUMN ESTPREV.ES_PLAN_EP IS 'ES PLANTILLA';

COMMENT ON COLUMN ESTPREV.DEP_DEL_EP IS 'Dependencia delegada para la contratación';

COMMENT ON COLUMN ESTPREV.ENPLANC_EP IS 'Incluido en el Plan de Compras';

COMMENT ON COLUMN ESTPREV.NOM_PLA_EP IS 'Nombre de Plantilla';

COMMENT ON COLUMN ESTPREV.ID_REV IS 'Ide del Ultimo Revisado';

COMMENT ON COLUMN ESTPREV.ID_APR IS 'Ide Del Ultimo Aprobado';

COMMENT ON COLUMN ESTPREV.OBLIGC IS 'Obligaciones del Contratista';

COMMENT ON COLUMN ESTPREV.OBLIGE IS 'Obligaciones Entidad';

COMMENT ON COLUMN ESTPREV.PERSONA_APOYO IS 'PERSONAL DE APOYO';

COMMENT ON COLUMN ESTPREV.ANTI_PORC IS 'PORCENTAJE DE ANTICIPO';

COMMENT ON COLUMN ESTPREV.TIPO_FP IS 'TIPO FORMA DE PAGO';

COMMENT ON COLUMN ESTPREV.IDE_CON_EP IS 'IDE DEL CONTRATISTA . CONTRATACIÓN DIRECTA';

COMMENT ON COLUMN ESTPREV.IDE_REP_EP IS 'IDE DEL REPRESENTANTE LEGAL';

COMMENT ON COLUMN ESTPREV.CAP_EXPERIENCA_EP IS 'Experiecia';

COMMENT ON COLUMN ESTPREV.NEC_CONT_INT_EP IS 'Necesidad de Contratar Interventor';

COMMENT ON COLUMN ESTPREV.SOM_ACUE_COMER_EP IS 'Sometiemiento Acuerdo Comercial';

COMMENT ON COLUMN ESTPREV.CONST_CUMP_DEBERES_EP IS 'Sometiemiento Acuerdo Comercial';

COMMENT ON COLUMN ESTPREV.IDE_SUP_EP IS 'Ide del Supervisor';

COMMENT ON COLUMN ESTPREV.CAR_SUP_EP IS 'Cargo Supervisor';

COMMENT ON COLUMN ESTPREV.COD_UNSPSC_EP IS 'Codigo UNSPSC';

COMMENT ON COLUMN ESTPREV.DES_UNSPSC_EP IS 'Descripción UNSPSC';

COMMENT ON COLUMN ESTPREV.ESP_OBJ_EP IS 'Especificación del Objeto a Contratar';

COMMENT ON COLUMN ESTPREV.AUTPERLIC_EP IS 'Autorizaciones, Permisos y Licencias ';

COMMENT ON COLUMN ESTPREV.DOCTECNICOS_EP IS 'Documentos Técnicos';

COMMENT ON COLUMN ESTPREV.VARIABLESPPTO_EP IS 'Variables Consideradar para el Presupuesto';

COMMENT ON COLUMN ESTPREV.ID IS 'Identificación del Estudio Previo';

COMMENT ON COLUMN ESTPREV.OBJE_EP IS 'Objeto a Contratar';

COMMENT ON COLUMN ESTPREV.PLAZ1_EP IS 'Plazo ';

COMMENT ON COLUMN ESTPREV.TPLA1_EP IS 'Tipo de Plazo';

COMMENT ON COLUMN ESTPREV.PLAZ2_EP IS 'Plazo ';

COMMENT ON COLUMN ESTPREV.TPLA2_EP IS 'Tipo de Plazo';

COMMENT ON COLUMN ESTPREV.LUGE_EP IS 'Lugar de Ejecución';

COMMENT ON COLUMN ESTPREV.PLIQ_EP IS 'Plazo de Liquidación';

COMMENT ON COLUMN ESTPREV.VAL_ENT_EP IS 'Valor Aportes Entidad';

COMMENT ON COLUMN ESTPREV.VAL_OTR_EP IS 'Valor Aportes Otros';

COMMENT ON COLUMN ESTPREV.IDE_DIL_EP IS 'Identificación del Funcionario quien Diligiencia el Estudio Previo';

COMMENT ON COLUMN ESTPREV.CAP_RESIDUAL_EP IS 'Capacidad Residual';

COMMENT ON COLUMN ESTPREV.PERS_LEGAL_EP IS 'Perspectiva Legal';

COMMENT ON COLUMN ESTPREV.PERS_ORGA_EP IS 'Perspectiva Organizacional';


CREATE UNIQUE INDEX ESTPREV_PK ON ESTPREV
(ID);


CREATE UNIQUE INDEX EP_COD_U01 ON ESTPREV
(CODIGO_EP);


ALTER TABLE ESTPREV ADD (
  CONSTRAINT ESTPREV_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ESTPREV ADD (
  CONSTRAINT EP_SUBTIPO 
 FOREIGN KEY (STIP_CON_EP) 
 REFERENCES SUBTIPOS (COD_STIP),
  CONSTRAINT EP_ELA_EP 
 FOREIGN KEY (USAP_ELA_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_IDE_REP_LEGAL 
 FOREIGN KEY (IDE_REP_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_CONTRATISTA 
 FOREIGN KEY (IDE_CON_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT ESTPREV_RES 
 FOREIGN KEY (IDE_RES_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_DAN_EP 
 FOREIGN KEY (USAP_DAN_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_APR_EP 
 FOREIGN KEY (USAP_APR_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_REV_EP 
 FOREIGN KEY (USAP_REV_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT EP_FUN_DIL 
 FOREIGN KEY (IDE_DIL_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT ESTPREV_TIP_PRO 
 FOREIGN KEY (MOD_SEL_EP) 
 REFERENCES TIPOSPROC (COD_TPROC),
  CONSTRAINT EP_TPLAZO2 
 FOREIGN KEY (TPLA2_EP) 
 REFERENCES TIPO_PLAZOS (COD_TPLA),
  CONSTRAINT EP_TPLAZO1 
 FOREIGN KEY (TPLA1_EP) 
 REFERENCES TIPO_PLAZOS (COD_TPLA),
  CONSTRAINT EP_DEPDEL 
 FOREIGN KEY (DEP_DEL_EP) 
 REFERENCES DEPENDENCIA (COD_DEP),
  CONSTRAINT EP_DEPSUP 
 FOREIGN KEY (DEP_SUP_EP) 
 REFERENCES DEPENDENCIA (COD_DEP),
  CONSTRAINT EP_DEP_NEC 
 FOREIGN KEY (DEP_NEC_EP) 
 REFERENCES DEPENDENCIA (COD_DEP),
  CONSTRAINT EP_ESTADO_FK 
 FOREIGN KEY (EST_EP) 
 REFERENCES EP_ESTADOS (COD_EST),
  CONSTRAINT ESTPREV_EFLU_FK 
 FOREIGN KEY (EST_FLU_EP) 
 REFERENCES EP_ESTFLU (COD_EST),
  CONSTRAINT EP_APR_FK 
 FOREIGN KEY (ID_APR) 
 REFERENCES EP_HESTADOEP (ID),
  CONSTRAINT EP_REV_FK 
 FOREIGN KEY (ID_REV) 
 REFERENCES EP_HESTADOEP (ID),
  CONSTRAINT ESTPREV_R01 
 FOREIGN KEY (IDE_SUP_EP) 
 REFERENCES TERCEROS (IDE_TER),
  CONSTRAINT ESTPREV_PAA 
 FOREIGN KEY (PAAID) 
 REFERENCES EP_PAA (ID));
