ALTER TABLE EST_RUTA ADD (
  CONSTRAINT EST_RUTA_INI 
 FOREIGN KEY (EST_INI) 
 REFERENCES ESTADOS (COD_EST));
 
 ALTER TABLE EST_RUTA ADD (
  CONSTRAINT ESTADOS_FIN 
 FOREIGN KEY (EST_FIN) 
 REFERENCES ESTADOS (COD_EST));