CREATE TABLE EP_CDP
(
  ID        NUMBER,
  ID_EP     NUMBER,
  NRO_CDP   VARCHAR2(10 BYTE)                   NOT NULL,
  FEC_CDP   DATE                                NOT NULL,
  VAL_CDP   NUMBER(17,3),
  VIG_FUT   VARCHAR2(2 BYTE),
  GRUPO     NUMBER,
  FEC_REG   DATE,
  USAP_REG  VARCHAR2(12 BYTE),
  FEC_MOD   DATE,
  USAP_MOD  VARCHAR2(12 BYTE)
);

COMMENT ON TABLE EP_CDP IS 'CDP DEL ESTUDIO PREVIO';

COMMENT ON COLUMN EP_CDP.ID IS 'IDE UNICO';

COMMENT ON COLUMN EP_CDP.ID_EP IS 'IDE DE ESTUDIO PREVIO';

COMMENT ON COLUMN EP_CDP.NRO_CDP IS 'NRO DEL CDP';

COMMENT ON COLUMN EP_CDP.FEC_CDP IS 'FECHA DEL CDP';

COMMENT ON COLUMN EP_CDP.VAL_CDP IS 'VALOR DEL CDP';

COMMENT ON COLUMN EP_CDP.VIG_FUT IS 'SI ES VIGENCIA FUTURA (SI/NO)';

COMMENT ON COLUMN EP_CDP.GRUPO IS 'GRUPO';

COMMENT ON COLUMN EP_CDP.FEC_REG IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN EP_CDP.USAP_REG IS 'USUARIO DEL REGISTRO';

COMMENT ON COLUMN EP_CDP.FEC_MOD IS 'FECHA DE MODIFICACIÓN';

COMMENT ON COLUMN EP_CDP.USAP_MOD IS 'USUARIO ULTIMA MODIFICACIÓN';


CREATE UNIQUE INDEX EP_CDP_PK ON EP_CDP
(ID);


CREATE UNIQUE INDEX EP_CDP_UK ON EP_CDP
(ID_EP, NRO_CDP);


ALTER TABLE EP_CDP ADD (
 CONSTRAINT EP_CDP_PK
 PRIMARY KEY
 (ID),
 CONSTRAINT EP_CDP_UK
 UNIQUE (ID_EP, NRO_CDP));

ALTER TABLE EP_CDP ADD (
  CONSTRAINT EP_CDP_EPFK 
 FOREIGN KEY (ID_EP) 
 REFERENCES ESTPREV (ID));
