ALTER TABLE PPLANTILLAS_FORMATO_TABLAS ADD (
  CONSTRAINT PPL_FMT_TAB_PK
 PRIMARY KEY
 (IDE_PLA, NTABLA, NOM_CAM));

ALTER TABLE PPLANTILLAS_FORMATO_TABLAS ADD (
  CONSTRAINT PPL_FMT_TAB_FKPP 
 FOREIGN KEY (IDE_PLA) 
 REFERENCES PPLANTILLAS (IDE_PLA));