CREATE TABLE INT_TRASLADOS
(
  ID       NUMBER,
  FEC_TRA  DATE,
  ORI_TRA  VARCHAR2(2 BYTE),
  DES_TRA  VARCHAR2(2 BYTE),
  USAP     VARCHAR2(20 BYTE),
  USAPM    VARCHAR2(20 BYTE),
  FEC_MOD  DATE,
  FEC_REG  DATE,
  EST_TRA  VARCHAR2(2 BYTE),
  OBS_TRA  VARCHAR2(200 BYTE)
);

COMMENT ON TABLE INT_TRASLADOS IS 'Traslados';

COMMENT ON COLUMN INT_TRASLADOS.ID IS 'Id unico';

COMMENT ON COLUMN INT_TRASLADOS.FEC_TRA IS 'Fecha del Traslado';

COMMENT ON COLUMN INT_TRASLADOS.ORI_TRA IS 'Origen ';

COMMENT ON COLUMN INT_TRASLADOS.DES_TRA IS 'Destino';

COMMENT ON COLUMN INT_TRASLADOS.USAP IS 'Usuario';

COMMENT ON COLUMN INT_TRASLADOS.USAPM IS 'Usuario ';

COMMENT ON COLUMN INT_TRASLADOS.FEC_MOD IS 'Fecha de Modificación';

COMMENT ON COLUMN INT_TRASLADOS.FEC_REG IS 'Fecha de Registro';

COMMENT ON COLUMN INT_TRASLADOS.EST_TRA IS 'Estado';

COMMENT ON COLUMN INT_TRASLADOS.OBS_TRA IS 'Observación';


CREATE UNIQUE INDEX INT_TRASLADOS_PK ON INT_TRASLADOS
(ID);


ALTER TABLE INT_TRASLADOS ADD (
  CONSTRAINT INT_TRASLADOS_PK
 PRIMARY KEY
 (ID));
