CREATE TABLE INT_INFOCONT
(
  COD_CON   VARCHAR2(10 BYTE),
  FEC_INF   DATE,
  FEC_INI   DATE,
  FEC_FIN   DATE,
  CAN_HOJ   NUMBER,
  NUM_INF   NUMBER,
  FE_REG    DATE                                DEFAULT sysdate,
  USAP      VARCHAR2(10 BYTE),
  USBD      VARCHAR2(20 BYTE)                   DEFAULT user,
  EST_INF   VARCHAR2(2 BYTE)                    DEFAULT 'AC',
  DES_INF   VARCHAR2(4000 BYTE),
  ID        NUMBER,
  NOT_INF   VARCHAR2(200 BYTE),
  VAL_PAG   NUMBER,
  OBL_FAC   VARCHAR2(2 BYTE),
  NOT2_INF  VARCHAR2(200 BYTE),
  ID_ACTA   NUMBER(10)
);

COMMENT ON COLUMN INT_INFOCONT.COD_CON IS 'Codigo del Contrato';

COMMENT ON COLUMN INT_INFOCONT.FEC_INF IS 'Fecha del Informe';

COMMENT ON COLUMN INT_INFOCONT.FEC_INI IS 'Fecha de Inicio del Periodo a Informar';

COMMENT ON COLUMN INT_INFOCONT.FEC_FIN IS 'Fecha de Fin del Periodo a Informar';

COMMENT ON COLUMN INT_INFOCONT.CAN_HOJ IS 'Cantidad de Hojas';

COMMENT ON COLUMN INT_INFOCONT.NUM_INF IS 'Número de Informe';

COMMENT ON COLUMN INT_INFOCONT.FE_REG IS 'Fecha de Registro de Informe';

COMMENT ON COLUMN INT_INFOCONT.USAP IS 'usuario app';

COMMENT ON COLUMN INT_INFOCONT.USBD IS 'usuario de la base de datos';

COMMENT ON COLUMN INT_INFOCONT.EST_INF IS 'Estado';

COMMENT ON COLUMN INT_INFOCONT.DES_INF IS 'descripcion o resumen  del Contratos';

COMMENT ON COLUMN INT_INFOCONT.ID IS 'identificador unico';

COMMENT ON COLUMN INT_INFOCONT.NOT_INF IS 'Nota Final';

COMMENT ON COLUMN INT_INFOCONT.VAL_PAG IS 'Valor Solicitado a pagar o valor cobrado';

COMMENT ON COLUMN INT_INFOCONT.OBL_FAC IS 'Obligado a Facturar';

COMMENT ON COLUMN INT_INFOCONT.NOT2_INF IS 'Nota 2 u observaiones adicionales';

COMMENT ON COLUMN INT_INFOCONT.ID_ACTA IS 'IDE DEL ACTA (ESTCONTRATOS)';


CREATE UNIQUE INDEX INT_INFOCONT_PK ON INT_INFOCONT
(ID);


ALTER TABLE INT_INFOCONT ADD (
  CONSTRAINT INT_INFOCONT_PK
 PRIMARY KEY
 (ID));

ALTER TABLE INT_INFOCONT ADD (
  CONSTRAINT INT_INFOCONT_R01 
 FOREIGN KEY (COD_CON) 
 REFERENCES CONTRATOS (COD_CON),
  CONSTRAINT INT_INF_ID_ACT 
 FOREIGN KEY (ID_ACTA) 
 REFERENCES ESTCONTRATOS (ID));
