CREATE TABLE INT_PAGOSST
(
  COD_CON      VARCHAR2(10 BYTE),
  TIPO_PLA     VARCHAR2(2 BYTE),
  PLANILLAN    VARCHAR2(20 BYTE),
  VAL_SALUD    NUMBER(17,2),
  VAL_PENSION  NUMBER(17,2),
  VAL_RIESGOS  NUMBER(17,2),
  VAL_PARAF    NUMBER(17,2),
  MES_PAGO     VARCHAR2(10 BYTE),
  YEAR_PAGO    VARCHAR2(4 BYTE),
  NRO_DOC      NUMBER,
  ID           NUMBER,
  USAP         VARCHAR2(20 BYTE),
  USBD         VARCHAR2(20 BYTE),
  FEC_REG      DATE,
  OBS          VARCHAR2(200 BYTE),
  FEC_MOD      DATE,
  USBDM        VARCHAR2(20 BYTE),
  USAPM        VARCHAR2(20 BYTE),
  ESTADO       VARCHAR2(2 BYTE)                 DEFAULT 'AC',
  IDE_INF      NUMBER
);

COMMENT ON TABLE INT_PAGOSST IS 'TABLA PARA EL REGISTRO DE DATOS DE APORTES DE SEGURIDAD SOCIAL DE TODOS LOS APORTES EN UN REGISTRO';

COMMENT ON COLUMN INT_PAGOSST.COD_CON IS 'codigo del contrato';

COMMENT ON COLUMN INT_PAGOSST.PLANILLAN IS 'numero de plantilla';

COMMENT ON COLUMN INT_PAGOSST.VAL_SALUD IS 'valor salud';

COMMENT ON COLUMN INT_PAGOSST.VAL_PENSION IS 'valor salud';

COMMENT ON COLUMN INT_PAGOSST.VAL_RIESGOS IS 'valor salud';

COMMENT ON COLUMN INT_PAGOSST.VAL_PARAF IS 'valor salud';

COMMENT ON COLUMN INT_PAGOSST.MES_PAGO IS 'mes de aporte';

COMMENT ON COLUMN INT_PAGOSST.YEAR_PAGO IS 'año de aporte';

COMMENT ON COLUMN INT_PAGOSST.NRO_DOC IS 'nro doc???';

COMMENT ON COLUMN INT_PAGOSST.ID IS 'id unico';

COMMENT ON COLUMN INT_PAGOSST.USAP IS 'usuario de aplicacion';

COMMENT ON COLUMN INT_PAGOSST.USBD IS 'usuario de bd';

COMMENT ON COLUMN INT_PAGOSST.FEC_REG IS 'feccha de registro';

COMMENT ON COLUMN INT_PAGOSST.OBS IS 'observacion ';

COMMENT ON COLUMN INT_PAGOSST.FEC_MOD IS 'fec de modificación';

COMMENT ON COLUMN INT_PAGOSST.USBDM IS 'usbd de modifiacion';

COMMENT ON COLUMN INT_PAGOSST.USAPM IS 'usap que modifica';

COMMENT ON COLUMN INT_PAGOSST.ESTADO IS 'ac o an';

COMMENT ON COLUMN INT_PAGOSST.IDE_INF IS 'ide del informe';


CREATE UNIQUE INDEX INT_PAGOSST_PK ON INT_PAGOSST
(ID);


ALTER TABLE INT_PAGOSST ADD (
  CONSTRAINT INT_PAGOSST_PK
 PRIMARY KEY
 (ID));

ALTER TABLE INT_PAGOSST ADD (
  CONSTRAINT INT_PAGOSST_CC 
 FOREIGN KEY (COD_CON) 
 REFERENCES CONTRATOS (COD_CON),
  CONSTRAINT INT_PAGOSST_IF 
 FOREIGN KEY (IDE_INF) 
 REFERENCES INT_INFOCONT (ID));