CREATE TABLE EP_DT_CAP_JUR
(
  EST_CAPJ  VARCHAR2(2 BYTE),
  DES_CAPJ  VARCHAR2(400 BYTE),
  ID        NUMBER
);

COMMENT ON TABLE EP_DT_CAP_JUR IS 'DATOS BASICOS PARA LA CAPACIDAD JURIDCA';

COMMENT ON COLUMN EP_DT_CAP_JUR.EST_CAPJ IS 'ESTADO DE LA CAPACIDAD JURIDICA';

COMMENT ON COLUMN EP_DT_CAP_JUR.DES_CAPJ IS 'DESCRIPCION DE LA CAPACIDAD JURIDICA';

COMMENT ON COLUMN EP_DT_CAP_JUR.ID IS 'ID';


CREATE UNIQUE INDEX EP_DT_CAP_JUR_PK ON EP_DT_CAP_JUR
(ID);


ALTER TABLE EP_DT_CAP_JUR ADD (
  CONSTRAINT EP_DT_CAP_JUR_PK
 PRIMARY KEY
 (ID));