CREATE TABLE ACTAPARCIAL
(
  ID_ACTA   NUMBER(10),
  FEC_PINI  DATE,
  FEC_PFIN  DATE,
  AUT_PAG   VARCHAR2(2 BYTE),
  VAL_AUT   NUMBER,
  FEC_REG   DATE,
  USAP      VARCHAR2(20 BYTE),
  FEC_MOD   DATE,
  USAP_MOD  VARCHAR2(20 BYTE)
);

COMMENT ON TABLE ACTAPARCIAL IS 'REGISTRO DE ACTAS PARCIAL / EN EJECUCIÓN';

COMMENT ON COLUMN ACTAPARCIAL.ID_ACTA IS 'IDE QUE IDENTIFICA EL ACTA EN ESTCONTRATOS';

COMMENT ON COLUMN ACTAPARCIAL.FEC_PINI IS 'FECHA INICIAL DEL PERIODO A CERTIFICAR';

COMMENT ON COLUMN ACTAPARCIAL.FEC_PFIN IS 'FECHA FINAL DEL PERIODO A CERTIFICAR';

COMMENT ON COLUMN ACTAPARCIAL.AUT_PAG IS 'AUTORIZACIÓN DEL PAGO?';

COMMENT ON COLUMN ACTAPARCIAL.FEC_REG IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN ACTAPARCIAL.USAP IS 'USUARIO QUIEN REGISTRA';

COMMENT ON COLUMN ACTAPARCIAL.FEC_MOD IS 'FECHA DE MODIFICACION';

COMMENT ON COLUMN ACTAPARCIAL.USAP_MOD IS 'USUARIO QUIEN MODIFICA';


ALTER TABLE ACTAPARCIAL ADD (
  PRIMARY KEY
 (ID_ACTA));

ALTER TABLE ACTAPARCIAL ADD (
  CONSTRAINT ACTAPARCIAL_FK 
 FOREIGN KEY (ID_ACTA) 
 REFERENCES ESTCONTRATOS (ID));
