CREATE TABLE INT_PPLANTILLAS_URL
(
  IDE_PLA     NUMBER,
  URL_FORM    VARCHAR2(200 BYTE),
  URL_RPTE    VARCHAR2(200 BYTE),
  URL_EST     VARCHAR2(2 BYTE),
  URL_DESC    VARCHAR2(200 BYTE),
  URL_FECREG  DATE,
  URL_USAP    VARCHAR2(20 BYTE),
  URL_USMD    VARCHAR2(20 BYTE),
  URL_FECMD   DATE
);

COMMENT ON TABLE INT_PPLANTILLAS_URL IS 'GESTION DE URL DE FORMULARIO';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.IDE_PLA IS 'IDE DE PLANTILLA';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_FORM IS 'URL DE FORMULARIO WEB';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_RPTE IS 'URL DEL REPORTE';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_EST IS 'ESTADO ';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_DESC IS 'DESCRIPCIÓN';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_FECREG IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_USAP IS 'USUARIO QUIEN CREO';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_USMD IS 'USUARIO QUIEN MODIFICO';

COMMENT ON COLUMN INT_PPLANTILLAS_URL.URL_FECMD IS 'FECHA QUIEN MODIFICO';


CREATE UNIQUE INDEX INT_PPLANTILLAS_URL_PK ON INT_PPLANTILLAS_URL
(IDE_PLA);


ALTER TABLE INT_PPLANTILLAS_URL ADD (
  CONSTRAINT INT_PPLANTILLAS_URL_PK
 PRIMARY KEY
 (IDE_PLA));

ALTER TABLE INT_PPLANTILLAS_URL ADD (
  CONSTRAINT INT_PPLANTILLAS_URL_FK 
 FOREIGN KEY (IDE_PLA) 
 REFERENCES PPLANTILLAS (IDE_PLA));