ALTER TABLE PACTIVIDADES
ADD (   
    TIPO    VARCHAR(2)
);

COMMENT ON COLUMN PACTIVIDADES.TIPO IS 'TIPO DE ACTIVIDAD: DO-> DOCUMENTO, SC-> SOLO COMPLETAR, DE-> DESCARTE';

ALTER TABLE PCRONOGRAMAS
ADD (   
    TIPO    VARCHAR(2)
);

COMMENT ON COLUMN PCRONOGRAMAS.TIPO IS 'TIPO DE ACTIVIDAD: DO-> DOCUMENTO, SC-> SOLO COMPLETAR, DE-> DESCARTE';

UPDATE PACTIVIDADES SET TIPO = 'SC' WHERE 1=1;

UPDATE PCRONOGRAMAS SET TIPO = 'SC' WHERE 1=1;

UPDATE PACTIVIDADES SET TIPO = 'DO' WHERE COD_TPRO = 'TP01' AND COD_ACT = '1';

UPDATE PACTIVIDADES SET TIPO = 'DO' WHERE COD_TPRO = 'TP01' AND COD_ACT = '18';

UPDATE PACTIVIDADES SET TIPO = 'DE' WHERE COD_TPRO = 'TP01' AND COD_ACT = '90';

COMMIT;