Insert into PL_TIPOS_PLANTILLA
   (COD_TIP, NOM_TIP)
 Values
   ('1', 'ACTA DE JUSTIFICACIÓN DE LA CONTRATACIÓN DIRECTA');
   
Insert into PL_TIPOS_PLANTILLA
   (COD_TIP, NOM_TIP)
 Values
   ('2', 'MINUTA');
COMMIT;
