CREATE USER SIRCC2
  IDENTIFIED BY SIRCC2
  DEFAULT TABLESPACE SIRCC_DATOS2
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO SIRCC2 WITH ADMIN OPTION;
  ALTER USER SIRCC2 DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO SIRCC2 WITH ADMIN OPTION;