//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Entidades
{
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTAPARCIAL> ACTAPARCIAL { get; set; }
        public DbSet<ADICIONES> ADICIONES { get; set; }
        public DbSet<AN_PCONTRATO> AN_PCONTRATO { get; set; }
        public DbSet<ANX_CONTRATOS> ANX_CONTRATOS { get; set; }
        public DbSet<ASEGURADORAS> ASEGURADORAS { get; set; }
        public DbSet<AUDI_CONTRATOS> AUDI_CONTRATOS { get; set; }
        public DbSet<AUDITORIA> AUDITORIA { get; set; }
        public DbSet<C_FORMA_PAGO> C_FORMA_PAGO { get; set; }
        public DbSet<C_POLIZAS2> C_POLIZAS2 { get; set; }
        public DbSet<C_RUBROS_CDP> C_RUBROS_CDP { get; set; }
        public DbSet<CAL_VIG_POL> CAL_VIG_POL { get; set; }
        public DbSet<CALCULOPOL> CALCULOPOL { get; set; }
        public DbSet<CDP_ADICIONES> CDP_ADICIONES { get; set; }
        public DbSet<CDP_CONTRATOS> CDP_CONTRATOS { get; set; }
        public DbSet<CDP_GPROCESOS> CDP_GPROCESOS { get; set; }
        public DbSet<CDP_PCONTRATOS> CDP_PCONTRATOS { get; set; }
        public DbSet<CESIONES> CESIONES { get; set; }
        public DbSet<CFORMA_PAGO> CFORMA_PAGO { get; set; }
        public DbSet<CMINUTAS> CMINUTAS { get; set; }
        public DbSet<COBLIGACIONES> COBLIGACIONES { get; set; }
        public DbSet<CON_POLIZAS> CON_POLIZAS { get; set; }
        public DbSet<CONFIGURACION> CONFIGURACION { get; set; }
        public DbSet<CONMUN> CONMUN { get; set; }
        public DbSet<CONS_PROC> CONS_PROC { get; set; }
        public DbSet<CONSORCIOSUT> CONSORCIOSUT { get; set; }
        public DbSet<CONSORCIOSUTXC> CONSORCIOSUTXC { get; set; }
        public DbSet<CONTRATOS> CONTRATOS { get; set; }
        public DbSet<CORREOSE> CORREOSE { get; set; }
        public DbSet<CPROYECTOS> CPROYECTOS { get; set; }
        public DbSet<CTRL_ENTIDAD> CTRL_ENTIDAD { get; set; }
        public DbSet<CUBRIMIENTO> CUBRIMIENTO { get; set; }
        public DbSet<DEPENDENCIA> DEPENDENCIA { get; set; }
        public DbSet<DOC_PLANTILLA> DOC_PLANTILLA { get; set; }
        public DbSet<DOC_SECCIONES> DOC_SECCIONES { get; set; }
        public DbSet<DOCPCONTRATOS> DOCPCONTRATOS { get; set; }
        public DbSet<DOCU_PROC> DOCU_PROC { get; set; }
        public DbSet<DT_PARAMETROS> DT_PARAMETROS { get; set; }
        public DbSet<EP_CAP_JUR> EP_CAP_JUR { get; set; }
        public DbSet<EP_CARGO> EP_CARGO { get; set; }
        public DbSet<EP_CDP> EP_CDP { get; set; }
        public DbSet<EP_CLAUSULAS> EP_CLAUSULAS { get; set; }
        public DbSet<EP_CODIGOSUNSPSC> EP_CODIGOSUNSPSC { get; set; }
        public DbSet<EP_CONMUN> EP_CONMUN { get; set; }
        public DbSet<EP_DT_CAP_JUR> EP_DT_CAP_JUR { get; set; }
        public DbSet<EP_DT_UNIDADES> EP_DT_UNIDADES { get; set; }
        public DbSet<EP_ESPTEC> EP_ESPTEC { get; set; }
        public DbSet<EP_ESTADOS> EP_ESTADOS { get; set; }
        public DbSet<EP_ESTFLU> EP_ESTFLU { get; set; }
        public DbSet<EP_FORMA_PAGO> EP_FORMA_PAGO { get; set; }
        public DbSet<EP_HESTADOEP> EP_HESTADOEP { get; set; }
        public DbSet<EP_MPAA> EP_MPAA { get; set; }
        public DbSet<EP_OBLIGACIONESC> EP_OBLIGACIONESC { get; set; }
        public DbSet<EP_OBLIGACIONESE> EP_OBLIGACIONESE { get; set; }
        public DbSet<EP_PAA> EP_PAA { get; set; }
        public DbSet<EP_PAA_UNSPSC> EP_PAA_UNSPSC { get; set; }
        public DbSet<EP_POLIZAS> EP_POLIZAS { get; set; }
        public DbSet<EP_POLIZAS2> EP_POLIZAS2 { get; set; }
        public DbSet<EP_PROYECTOS> EP_PROYECTOS { get; set; }
        public DbSet<EP_RIESGOS> EP_RIESGOS { get; set; }
        public DbSet<EP_RUBROS_CDP> EP_RUBROS_CDP { get; set; }
        public DbSet<EP_UNSPSC> EP_UNSPSC { get; set; }
        public DbSet<ESTADOS> ESTADOS { get; set; }
        public DbSet<ESTADOSGENERALES> ESTADOSGENERALES { get; set; }
        public DbSet<ESTCONTRATOS> ESTCONTRATOS { get; set; }
        public DbSet<ESTPREV> ESTPREV { get; set; }
        public DbSet<ETAPAS> ETAPAS { get; set; }
        public DbSet<GD_CT_OFICIOS> GD_CT_OFICIOS { get; set; }
        public DbSet<GD_DDOCUMENTOS> GD_DDOCUMENTOS { get; set; }
        public DbSet<GD_DOC_ACTAS> GD_DOC_ACTAS { get; set; }
        public DbSet<GD_DOCUMENTOS> GD_DOCUMENTOS { get; set; }
        public DbSet<GPOBLIGACIONES> GPOBLIGACIONES { get; set; }
        public DbSet<GPPOLIZAS> GPPOLIZAS { get; set; }
        public DbSet<GPPROPONENTES> GPPROPONENTES { get; set; }
        public DbSet<GPPROYECTOS> GPPROYECTOS { get; set; }
        public DbSet<GPROCESOS> GPROCESOS { get; set; }
        public DbSet<GR_TIP_OFI> GR_TIP_OFI { get; set; }
        public DbSet<HAUDITORIA> HAUDITORIA { get; set; }
        public DbSet<HCONTRATOS> HCONTRATOS { get; set; }
        public DbSet<HDEP_ABOGADOS> HDEP_ABOGADOS { get; set; }
        public DbSet<HMOD_CONTRATOS> HMOD_CONTRATOS { get; set; }
        public DbSet<HOJAS_RUTAS> HOJAS_RUTAS { get; set; }
        public DbSet<HORAS> HORAS { get; set; }
        public DbSet<HREVISADO> HREVISADO { get; set; }
        public DbSet<HREVSOLADI> HREVSOLADI { get; set; }
        public DbSet<IMP_ADICIONES> IMP_ADICIONES { get; set; }
        public DbSet<IMP_CONTRATOS> IMP_CONTRATOS { get; set; }
        public DbSet<IMPUESTOS> IMPUESTOS { get; set; }
        public DbSet<INT_CONTROL_DOC> INT_CONTROL_DOC { get; set; }
        public DbSet<INT_DETCUENTA> INT_DETCUENTA { get; set; }
        public DbSet<INT_DETTRASLADO> INT_DETTRASLADO { get; set; }
        public DbSet<INT_INFOCONT> INT_INFOCONT { get; set; }
        public DbSet<INT_PAGOSST> INT_PAGOSST { get; set; }
        public DbSet<INT_PPLANTILLAS_URL> INT_PPLANTILLAS_URL { get; set; }
        public DbSet<INT_TRASLADOS> INT_TRASLADOS { get; set; }
        public DbSet<INTERVENTORES_CONTRATO> INTERVENTORES_CONTRATO { get; set; }
        public DbSet<INTTIPO_ESS> INTTIPO_ESS { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MENU_PERFIL> MENU_PERFIL { get; set; }
        public DbSet<MENU2> MENU2 { get; set; }
        public DbSet<MENUMB> MENUMB { get; set; }
        public DbSet<MIN_MOD_CONTRATO> MIN_MOD_CONTRATO { get; set; }
        public DbSet<MOD_CDP_CONTRATOS> MOD_CDP_CONTRATOS { get; set; }
        public DbSet<MOD_CFORMA_PAGO> MOD_CFORMA_PAGO { get; set; }
        public DbSet<MOD_COBLIGACIONES> MOD_COBLIGACIONES { get; set; }
        public DbSet<MOD_CON_POLIZAS> MOD_CON_POLIZAS { get; set; }
        public DbSet<MOD_CONMUN> MOD_CONMUN { get; set; }
        public DbSet<MOD_CONTRATOS> MOD_CONTRATOS { get; set; }
        public DbSet<MOD_CPROYECTOS> MOD_CPROYECTOS { get; set; }
        public DbSet<MOD_PROPONENTES> MOD_PROPONENTES { get; set; }
        public DbSet<MOD_TIP_PLA> MOD_TIP_PLA { get; set; }
        public DbSet<MODULOS> MODULOS { get; set; }
        public DbSet<MUNICIPIOS> MUNICIPIOS { get; set; }
        public DbSet<NROCONVIG> NROCONVIG { get; set; }
        public DbSet<NUMPROP> NUMPROP { get; set; }
        public DbSet<ORA_ASPNET_APPLICATIONS> ORA_ASPNET_APPLICATIONS { get; set; }
        public DbSet<ORA_ASPNET_MEMBERSHIP> ORA_ASPNET_MEMBERSHIP { get; set; }
        public DbSet<ORA_ASPNET_PATHS> ORA_ASPNET_PATHS { get; set; }
        public DbSet<ORA_ASPNET_PERSONALIZNALLUSERS> ORA_ASPNET_PERSONALIZNALLUSERS { get; set; }
        public DbSet<ORA_ASPNET_PERSONALIZNPERUSER> ORA_ASPNET_PERSONALIZNPERUSER { get; set; }
        public DbSet<ORA_ASPNET_PROFILE> ORA_ASPNET_PROFILE { get; set; }
        public DbSet<ORA_ASPNET_ROLES> ORA_ASPNET_ROLES { get; set; }
        public DbSet<ORA_ASPNET_SESSIONAPPLICATIONS> ORA_ASPNET_SESSIONAPPLICATIONS { get; set; }
        public DbSet<ORA_ASPNET_SESSIONS> ORA_ASPNET_SESSIONS { get; set; }
        public DbSet<ORA_ASPNET_SITEMAP> ORA_ASPNET_SITEMAP { get; set; }
        public DbSet<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
        public DbSet<PACTIVIDADES> PACTIVIDADES { get; set; }
        public DbSet<PAGAUT> PAGAUT { get; set; }
        public DbSet<PAGOS_GPROCESOS> PAGOS_GPROCESOS { get; set; }
        public DbSet<PAGOS_PARCIALES> PAGOS_PARCIALES { get; set; }
        public DbSet<PCLAUSULAS> PCLAUSULAS { get; set; }
        public DbSet<PCONMUN> PCONMUN { get; set; }
        public DbSet<PCONTRATOS> PCONTRATOS { get; set; }
        public DbSet<PCRONO_DIAS> PCRONO_DIAS { get; set; }
        public DbSet<PCRONOGRAMAS> PCRONOGRAMAS { get; set; }
        public DbSet<PESTADOS> PESTADOS { get; set; }
        public DbSet<PESTADOSACT> PESTADOSACT { get; set; }
        public DbSet<PGCONTRATOSM> PGCONTRATOSM { get; set; }
        public DbSet<PL_PLANTILLA> PL_PLANTILLA { get; set; }
        public DbSet<PL_SECCIONES> PL_SECCIONES { get; set; }
        public DbSet<PL_TIPOS_PLANTILLA> PL_TIPOS_PLANTILLA { get; set; }
        public DbSet<PLANTILLAPPAL> PLANTILLAPPAL { get; set; }
        public DbSet<POBLIGACIONES> POBLIGACIONES { get; set; }
        public DbSet<POLIZAS> POLIZAS { get; set; }
        public DbSet<POLIZAS_ADICIONES> POLIZAS_ADICIONES { get; set; }
        public DbSet<POLIZAS_CONTRATO> POLIZAS_CONTRATO { get; set; }
        public DbSet<PPLANTILLAS> PPLANTILLAS { get; set; }
        public DbSet<PPLANTILLAS_CAMPOS> PPLANTILLAS_CAMPOS { get; set; }
        public DbSet<PPLANTILLAS_FORMATO_TABLAS> PPLANTILLAS_FORMATO_TABLAS { get; set; }
        public DbSet<PPOLIZAS> PPOLIZAS { get; set; }
        public DbSet<PPROPONENTES> PPROPONENTES { get; set; }
        public DbSet<PPROPONENTESS> PPROPONENTESS { get; set; }
        public DbSet<PR_DB_CLAUSULAS> PR_DB_CLAUSULAS { get; set; }
        public DbSet<PROYECTOS> PROYECTOS { get; set; }
        public DbSet<PSOLICITUDES> PSOLICITUDES { get; set; }
        public DbSet<PUNIDADES> PUNIDADES { get; set; }
        public DbSet<RP> RP { get; set; }
        public DbSet<RP_ADICIONES> RP_ADICIONES { get; set; }
        public DbSet<RP_CONTRATOS> RP_CONTRATOS { get; set; }
        public DbSet<RP_CONTRATOS_A> RP_CONTRATOS_A { get; set; }
        public DbSet<RPT_CONTROL> RPT_CONTROL { get; set; }
        public DbSet<RUBROS> RUBROS { get; set; }
        public DbSet<RUBROS_ADICIONES> RUBROS_ADICIONES { get; set; }
        public DbSet<RUBROS_CONTRATOS> RUBROS_CONTRATOS { get; set; }
        public DbSet<RUBROS_CONTRATOS_2008_2010> RUBROS_CONTRATOS_2008_2010 { get; set; }
        public DbSet<RUBROS_CONTRATOS_X> RUBROS_CONTRATOS_X { get; set; }
        public DbSet<RUBROS_GPROCESOS> RUBROS_GPROCESOS { get; set; }
        public DbSet<RUBROS_PCONTRATOS> RUBROS_PCONTRATOS { get; set; }
        public DbSet<RUBROS_RCONTRATOS> RUBROS_RCONTRATOS { get; set; }
        public DbSet<SECTOR> SECTOR { get; set; }
        public DbSet<SOL_ADICIONES> SOL_ADICIONES { get; set; }
        public DbSet<SUBTIPOS> SUBTIPOS { get; set; }
        public DbSet<TERCEROS> TERCEROS { get; set; }
        public DbSet<TERCEROSDESKTOP> TERCEROSDESKTOP { get; set; }
        public DbSet<TIP_DOC> TIP_DOC { get; set; }
        public DbSet<TIPO_ADCIONES> TIPO_ADCIONES { get; set; }
        public DbSet<TIPO_AGENT> TIPO_AGENT { get; set; }
        public DbSet<TIPO_INTERVENTOR> TIPO_INTERVENTOR { get; set; }
        public DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
        public DbSet<TIPO_PLAZOS> TIPO_PLAZOS { get; set; }
        public DbSet<TIPOSCONT> TIPOSCONT { get; set; }
        public DbSet<TIPOSGASTOS> TIPOSGASTOS { get; set; }
        public DbSet<TIPOSPROC> TIPOSPROC { get; set; }
        public DbSet<TIPPLANTILLAS> TIPPLANTILLAS { get; set; }
        public DbSet<TIPPROPONENTE> TIPPROPONENTE { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VIGENCIAS> VIGENCIAS { get; set; }
    }
}
