//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class ACTAPARCIAL
    {
        public int ID_ACTA { get; set; }
        public Nullable<System.DateTime> FEC_PINI { get; set; }
        public Nullable<System.DateTime> FEC_PFIN { get; set; }
        public string AUT_PAG { get; set; }
        public Nullable<decimal> VAL_AUT { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP_MOD { get; set; }
    
        public virtual ESTCONTRATOS ESTCONTRATOS { get; set; }
    }
    
}
