//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class C_POLIZAS2
    {
        public decimal ID { get; set; }
        public Nullable<int> COD_POL { get; set; }
        public string DES_POL { get; set; }
        public string PLA_POL { get; set; }
        public string VAL_POL { get; set; }
        public Nullable<int> GRUPO { get; set; }
        public string COD_CON { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual POLIZAS POLIZAS { get; set; }
    }
    
}
