//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CDP_CONTRATOS
    {
        public CDP_CONTRATOS()
        {
            this.C_RUBROS_CDP = new HashSet<C_RUBROS_CDP>();
            this.RP_CONTRATOS = new HashSet<RP_CONTRATOS>();
        }
    
        public string NRO_CDP { get; set; }
        public string COD_CON { get; set; }
        public System.DateTime FEC_CDP { get; set; }
        public Nullable<decimal> VAL_CDP { get; set; }
        public string VIG_FUT { get; set; }
    
        public virtual ICollection<C_RUBROS_CDP> C_RUBROS_CDP { get; set; }
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual ICollection<RP_CONTRATOS> RP_CONTRATOS { get; set; }
    }
    
}
