//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class CESIONES
    {
        public string NIT_ANT { get; set; }
        public string NIT_NUE { get; set; }
        public Nullable<int> PLA_CES { get; set; }
        public Nullable<int> VAL_CES { get; set; }
        public Nullable<System.DateTime> FEC_CES { get; set; }
        public string RES_AUT { get; set; }
        public string COD_CON { get; set; }
        public Nullable<System.DateTime> FEC_RES { get; set; }
    }
    
}
