//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class DOC_PLANTILLA
    {
        public DOC_PLANTILLA()
        {
            this.DOC_SECCIONES = new HashSet<DOC_SECCIONES>();
        }
    
        public decimal ID { get; set; }
        public string NRO_DOC { get; set; }
        public string COD_TIP { get; set; }
        public string TITULO { get; set; }
        public Nullable<System.DateTime> FEC_REV { get; set; }
        public string NRO_REV { get; set; }
        public string EST_DOC { get; set; }
        public Nullable<System.DateTime> FEC_DOC { get; set; }
        public string NUM_PROC { get; set; }
        public Nullable<decimal> ID_PLA { get; set; }
        public string EST_COMPLETADO { get; set; }
    
        public virtual PL_TIPOS_PLANTILLA PL_TIPOS_PLANTILLA { get; set; }
        public virtual PCONTRATOS PCONTRATOS { get; set; }
        public virtual ICollection<DOC_SECCIONES> DOC_SECCIONES { get; set; }
        public virtual PL_PLANTILLA PL_PLANTILLA { get; set; }
    }
    
}
