//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_CARGO
    {
        public string COD_CARGO { get; set; }
        public string DES_CARGO { get; set; }
        public string VIG_CARGO { get; set; }
        public string EST_CARGO { get; set; }
    }
    
}
