//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_CODIGOSUNSPSC
    {
        public EP_CODIGOSUNSPSC()
        {
            this.EP_CODIGOSUNSPSC1 = new HashSet<EP_CODIGOSUNSPSC>();
            this.EP_PAA_UNSPSC = new HashSet<EP_PAA_UNSPSC>();
            this.EP_UNSPSC = new HashSet<EP_UNSPSC>();
        }
    
        public string UNSPSC { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CLASIFICADOR { get; set; }
        public string PADRE { get; set; }
    
        public virtual ICollection<EP_CODIGOSUNSPSC> EP_CODIGOSUNSPSC1 { get; set; }
        public virtual EP_CODIGOSUNSPSC EP_CODIGOSUNSPSC2 { get; set; }
        public virtual ICollection<EP_PAA_UNSPSC> EP_PAA_UNSPSC { get; set; }
        public virtual ICollection<EP_UNSPSC> EP_UNSPSC { get; set; }
    }
    
}
