//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_CLAUSULAS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_PLA { get; set; }
        public string TIP_PLA { get; set; }
        public string CLA_TIT { get; set; }
        public Nullable<decimal> CLA_NUM { get; set; }
        public string CLA_CAM { get; set; }
        public string CLA_PAR { get; set; }
        public Nullable<decimal> IDE_PMIN { get; set; }
        public string TIP_PAR { get; set; }
        public string IS_ENTER_FINAL { get; set; }
        public Nullable<short> ORDEN { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public string CLA_TEXTO { get; set; }
        public string CLA_CRUZADA { get; set; }
    
        public virtual ESTPREV ESTPREV { get; set; }
    }
    
}
