//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_MPAA
    {
        public EP_MPAA()
        {
            this.EP_PAA = new HashSet<EP_PAA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<short> VIGENCIA { get; set; }
        public string OBSERV { get; set; }
        public Nullable<System.DateTime> FEC_INI { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public string ESTADO { get; set; }
        public string COD_SECOP { get; set; }
    
        public virtual ICollection<EP_PAA> EP_PAA { get; set; }
    }
    
}
