//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_PAA
    {
        public EP_PAA()
        {
            this.EP_PAA_UNSPSC = new HashSet<EP_PAA_UNSPSC>();
            this.ESTPREV = new HashSet<ESTPREV>();
        }
    
        public int ID { get; set; }
        public Nullable<short> VIGENCIA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FEC_EST_INI { get; set; }
        public Nullable<decimal> PLA1_EJE { get; set; }
        public string TIP1_PLA { get; set; }
        public Nullable<decimal> PLA2_EJE { get; set; }
        public string TIP2_PLA { get; set; }
        public string MOD_SEL { get; set; }
        public string FUE_SEL { get; set; }
        public Nullable<decimal> VAL_TOT_EST { get; set; }
        public Nullable<decimal> VAL_VIG_EST { get; set; }
        public string VIG_FUT { get; set; }
        public string EST_SOL_VF { get; set; }
        public string DAT_RESPONSABLE { get; set; }
        public string COD_DEP { get; set; }
        public Nullable<decimal> ID_EP_MPAA { get; set; }
    
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        public virtual EP_MPAA EP_MPAA { get; set; }
        public virtual ICollection<EP_PAA_UNSPSC> EP_PAA_UNSPSC { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
    }
    
}
