//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class EP_UNSPSC
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_EP { get; set; }
        public string UNSPSC { get; set; }
    
        public virtual EP_CODIGOSUNSPSC EP_CODIGOSUNSPSC { get; set; }
        public virtual ESTPREV ESTPREV { get; set; }
    }
    
}
