//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GD_CT_OFICIOS
    {
        public Nullable<System.DateTime> FEC_OFI { get; set; }
        public string COD_CON { get; set; }
        public string TIP_OFI { get; set; }
        public string EST_OFI { get; set; }
        public decimal ID { get; set; }
    }
    
}
