//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GD_DOCUMENTOS
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> LONGITUD { get; set; }
        public string TYPE { get; set; }
        public string URL { get; set; }
        public string DESCRIPCION { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string ESTADO { get; set; }
    
        public virtual GD_DDOCUMENTOS GD_DDOCUMENTOS { get; set; }
    }
    
}
