//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GD_DOC_ACTAS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_DOC { get; set; }
        public string COD_CON { get; set; }
        public Nullable<decimal> ID_INF { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USAP { get; set; }
        public string EST_REL { get; set; }
        public string TIP_DOC { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual INT_INFOCONT INT_INFOCONT { get; set; }
        public virtual TIP_DOC TIP_DOC1 { get; set; }
    }
    
}
