//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class GR_TIP_OFI
    {
        public string TIP_OFI { get; set; }
        public string NOM_OFI { get; set; }
        public string ETA_OFI { get; set; }
    }
    
}
