//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_INFOCONT
    {
        public INT_INFOCONT()
        {
            this.GD_DOC_ACTAS = new HashSet<GD_DOC_ACTAS>();
            this.INT_PAGOSST = new HashSet<INT_PAGOSST>();
        }
    
        public string COD_CON { get; set; }
        public Nullable<System.DateTime> FEC_INF { get; set; }
        public Nullable<System.DateTime> FEC_INI { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public Nullable<decimal> CAN_HOJ { get; set; }
        public Nullable<decimal> NUM_INF { get; set; }
        public Nullable<System.DateTime> FE_REG { get; set; }
        public string USAP { get; set; }
        public string USBD { get; set; }
        public string EST_INF { get; set; }
        public string DES_INF { get; set; }
        public decimal ID { get; set; }
        public string NOT_INF { get; set; }
        public Nullable<decimal> VAL_PAG { get; set; }
        public string OBL_FAC { get; set; }
        public string NOT2_INF { get; set; }
        public Nullable<int> ID_ACTA { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual ESTCONTRATOS ESTCONTRATOS { get; set; }
        public virtual ICollection<GD_DOC_ACTAS> GD_DOC_ACTAS { get; set; }
        public virtual ICollection<INT_PAGOSST> INT_PAGOSST { get; set; }
    }
    
}
