//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_DETCUENTA
    {
        public decimal ID { get; set; }
        public int IDACTA { get; set; }
        public string NRO_RP { get; set; }
        public string NRO_OP { get; set; }
        public Nullable<decimal> VAL_OP { get; set; }
        public Nullable<System.DateTime> FEC_OP { get; set; }
        public Nullable<System.DateTime> FEC_CAU { get; set; }
        public string NRO_EGR { get; set; }
        public Nullable<System.DateTime> FEC_EGR { get; set; }
        public string EST_EGR { get; set; }
        public Nullable<short> VIG_RP { get; set; }
        public Nullable<decimal> ID_CTRDOC { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP { get; set; }
        public string USAPM { get; set; }
    
        public virtual ESTCONTRATOS ESTCONTRATOS { get; set; }
        public virtual INT_CONTROL_DOC INT_CONTROL_DOC { get; set; }
    }
    
}
