//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_CONTROL_DOC
    {
        public INT_CONTROL_DOC()
        {
            this.ESTCONTRATOS = new HashSet<ESTCONTRATOS>();
            this.INT_CONTROL_DOC1 = new HashSet<INT_CONTROL_DOC>();
            this.INT_DETTRASLADO = new HashSet<INT_DETTRASLADO>();
            this.INT_DETTRASLADO1 = new HashSet<INT_DETTRASLADO>();
            this.INT_DETCUENTA = new HashSet<INT_DETCUENTA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> IDACTA { get; set; }
        public Nullable<System.DateTime> FEC_REC { get; set; }
        public Nullable<System.DateTime> FEC_REC_SIS { get; set; }
        public string OBS_REC { get; set; }
        public string EST_DOC { get; set; }
        public string ETA_DOC { get; set; }
        public Nullable<System.DateTime> FEC_REV { get; set; }
        public string OBS_REV { get; set; }
        public string USAP_REC { get; set; }
        public string USAP_REV { get; set; }
        public string USAP_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public Nullable<System.DateTime> FEC_REV_SIS { get; set; }
        public Nullable<decimal> IDPADRE { get; set; }
        public string EST_REG { get; set; }
    
        public virtual ICollection<ESTCONTRATOS> ESTCONTRATOS { get; set; }
        public virtual ESTCONTRATOS ESTCONTRATOS1 { get; set; }
        public virtual ICollection<INT_CONTROL_DOC> INT_CONTROL_DOC1 { get; set; }
        public virtual INT_CONTROL_DOC INT_CONTROL_DOC2 { get; set; }
        public virtual ICollection<INT_DETTRASLADO> INT_DETTRASLADO { get; set; }
        public virtual ICollection<INT_DETTRASLADO> INT_DETTRASLADO1 { get; set; }
        public virtual ICollection<INT_DETCUENTA> INT_DETCUENTA { get; set; }
    }
    
}
