//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class INT_TRASLADOS
    {
        public INT_TRASLADOS()
        {
            this.INT_DETTRASLADO = new HashSet<INT_DETTRASLADO>();
        }
    
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FEC_TRA { get; set; }
        public string ORI_TRA { get; set; }
        public string DES_TRA { get; set; }
        public string USAP { get; set; }
        public string USAPM { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string EST_TRA { get; set; }
        public string OBS_TRA { get; set; }
    
        public virtual ICollection<INT_DETTRASLADO> INT_DETTRASLADO { get; set; }
    }
    
}
