//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class MOD_TIP_PLA
    {
        public string COD_MOD { get; set; }
        public string COD_TIP { get; set; }
        public string EST { get; set; }
    
        public virtual TIPOSPROC TIPOSPROC { get; set; }
        public virtual PL_TIPOS_PLANTILLA PL_TIPOS_PLANTILLA { get; set; }
    }
    
}
