//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class PL_TIPOS_PLANTILLA
    {
        public PL_TIPOS_PLANTILLA()
        {
            this.DOC_PLANTILLA = new HashSet<DOC_PLANTILLA>();
            this.MOD_TIP_PLA = new HashSet<MOD_TIP_PLA>();
            this.PACTIVIDADES = new HashSet<PACTIVIDADES>();
            this.PCRONOGRAMAS = new HashSet<PCRONOGRAMAS>();
            this.PL_PLANTILLA = new HashSet<PL_PLANTILLA>();
        }
    
        public string COD_TIP { get; set; }
        public string NOM_TIP { get; set; }
    
        public virtual ICollection<DOC_PLANTILLA> DOC_PLANTILLA { get; set; }
        public virtual ICollection<MOD_TIP_PLA> MOD_TIP_PLA { get; set; }
        public virtual ICollection<PACTIVIDADES> PACTIVIDADES { get; set; }
        public virtual ICollection<PCRONOGRAMAS> PCRONOGRAMAS { get; set; }
        public virtual ICollection<PL_PLANTILLA> PL_PLANTILLA { get; set; }
    }
    
}
