//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class RPT_CONTROL
    {
        public Nullable<decimal> VIG_RPT { get; set; }
        public decimal ID { get; set; }
        public string IDE_RPT { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SQL { get; set; }
        public string DESC_RPT { get; set; }
        public string EST_RPT { get; set; }
        public string ENT_RPT { get; set; }
    }
    
}
