//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class TERCEROS
    {
        public TERCEROS()
        {
            this.CONSORCIOSUT = new HashSet<CONSORCIOSUT>();
            this.CONSORCIOSUTXC = new HashSet<CONSORCIOSUTXC>();
            this.CONSORCIOSUTXC1 = new HashSet<CONSORCIOSUTXC>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.ESTPREV = new HashSet<ESTPREV>();
            this.ESTPREV1 = new HashSet<ESTPREV>();
            this.ESTPREV2 = new HashSet<ESTPREV>();
            this.ESTPREV3 = new HashSet<ESTPREV>();
            this.ESTPREV4 = new HashSet<ESTPREV>();
            this.ESTPREV5 = new HashSet<ESTPREV>();
            this.ESTPREV6 = new HashSet<ESTPREV>();
            this.ESTPREV7 = new HashSet<ESTPREV>();
            this.ESTPREV8 = new HashSet<ESTPREV>();
            this.HDEP_ABOGADOS = new HashSet<HDEP_ABOGADOS>();
            this.HREVISADO = new HashSet<HREVISADO>();
            this.INTERVENTORES_CONTRATO = new HashSet<INTERVENTORES_CONTRATO>();
            this.PCONTRATOS = new HashSet<PCONTRATOS>();
            this.PPROPONENTESS = new HashSet<PPROPONENTESS>();
            this.PPROPONENTESS1 = new HashSet<PPROPONENTESS>();
            this.PSOLICITUDES = new HashSet<PSOLICITUDES>();
            this.PSOLICITUDES1 = new HashSet<PSOLICITUDES>();
            this.CONTRATOS1 = new HashSet<CONTRATOS>();
        }
    
        public string IDE_TER { get; set; }
        public string APE1_TER { get; set; }
        public string DIR_TER { get; set; }
        public string TEL_TER { get; set; }
        public string EMA_TER { get; set; }
        public string APE2_TER { get; set; }
        public string NOM1_TER { get; set; }
        public string NOM2_TER { get; set; }
        public string TIP_IDE { get; set; }
        public string EXP_IDE { get; set; }
        public string DV_TER { get; set; }
        public string RAZ_SOC { get; set; }
        public string ORD_GAS { get; set; }
        public string CAR_FUN { get; set; }
        public string DOC_DEL { get; set; }
        public Nullable<System.DateTime> FEC_DEL { get; set; }
        public string DEP_NEC { get; set; }
        public string ESTADO { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FEC_NAC { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string USAP { get; set; }
        public string USAPM { get; set; }
        public string TIP_PER { get; set; }
    
        public virtual ICollection<CONSORCIOSUT> CONSORCIOSUT { get; set; }
        public virtual ICollection<CONSORCIOSUTXC> CONSORCIOSUTXC { get; set; }
        public virtual ICollection<CONSORCIOSUTXC> CONSORCIOSUTXC1 { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV1 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV2 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV3 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV4 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV5 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV6 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV7 { get; set; }
        public virtual ICollection<ESTPREV> ESTPREV8 { get; set; }
        public virtual ICollection<HDEP_ABOGADOS> HDEP_ABOGADOS { get; set; }
        public virtual ICollection<HREVISADO> HREVISADO { get; set; }
        public virtual ICollection<INTERVENTORES_CONTRATO> INTERVENTORES_CONTRATO { get; set; }
        public virtual ICollection<PCONTRATOS> PCONTRATOS { get; set; }
        public virtual ICollection<PPROPONENTESS> PPROPONENTESS { get; set; }
        public virtual ICollection<PPROPONENTESS> PPROPONENTESS1 { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES { get; set; }
        public virtual ICollection<PSOLICITUDES> PSOLICITUDES1 { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS1 { get; set; }
    }
    
}
