//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class VIGENCIAS
    {
        public short YEAR_VIG { get; set; }
        public System.DateTime FEC_INI_VIG { get; set; }
        public Nullable<System.DateTime> FEC_FIN_VIG { get; set; }
        public short POR_ADI_VIG { get; set; }
        public string EST_VIG { get; set; }
        public string RAD_AUT { get; set; }
    }
    
}
