CREATE USER SIRCC_MIG
  IDENTIFIED BY SIRCC_MIG
  DEFAULT TABLESPACE SIRCC_DATOS_MIGRACION
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO SIRCC_MIG WITH ADMIN OPTION;
  ALTER USER SIRCC_MIG DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO SIRCC_MIG WITH ADMIN OPTION;