CREATE TABLESPACE SIRCC_DATOS_MIGRACION DATAFILE 
  'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SIRCC_DATOS_MIGRACION.ORA' SIZE 400M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;