//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Financiero
{
    public partial class DORDEN
    {
        public decimal VIGENCIA { get; set; }
        public decimal NUM_ORDEN { get; set; }
        public string COD_UNIDAD { get; set; }
        public string COD_GASTO { get; set; }
        public string COD_RECURSO { get; set; }
        public decimal VAL_ORDEN { get; set; }
        public decimal VAL_AMORTIZADO { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FEC_OPERACION { get; set; }
    }
    
}
